version: "~> 1.0"
git:
    depth: 1
    quiet: true
dist: jammy
language: java
jdk:
    - openjdk21
branches:
    only:
        - develop
        - support/4.1
cache:
    directories:
        - "$HOME/.m2"
        - "$HOME/downloads"
notifications:
    slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
    - mkdir -p $HOME/.m2
    - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
    - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn -Dmaven.javadoc.skip=true clean deploy -DcloneUi=true --settings .travis-settings.xml; fi
    - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then mvn -Dmaven.javadoc.skip=true clean install -DcloneUi=true; fi
env:
    global:
        - secure: "etDaXgWp7fCO8jUy9zI+SJf0lXIt6X3xRZI63VuXkFETEGBsrEopmolLawyzcJ+dAqPcflj1okfT7VuXruy1f5Nrkk3QVgqy0yBD3ixHRlqG3CXZyStIOAO58Q1oAY4PleVHsHStwSQV80Gy4p+k/MBFk/H1m6P73Kzj2CayEIo="
        - secure: "G3lgCxcNsFff8YBWG0ZG1bYXDBejCdW8IXRpTYy/2HugvDDcV42XCYzXpttVmFbUQx9j6QZnI/4OKDassy8Xsg//TItwTLdGi/Xl/U6IEVRLQsFOUDrsx0zKo9bJmR42Daluqngz9C+WiQZQGyOsqWSPcuuTY7pHFOK46QT+Yy0="
