version: "~> 1.0"
git:
  depth: 1
  quiet: true
dist: jammy
language: java
jdk:
  - openjdk21
branches:
  only:
    - develop
    - support/4.x
cache:
  directories:
    - "$HOME/.m2"
    - "$HOME/downloads"
notifications:
  slack: craftersoftware:7YiSb41ZG5rfMgiAY7Qgprc7
before_install:
  - mkdir -p $HOME/.m2
  - cp .travis-settings.xml $HOME/.m2/settings.xml
install: skip
script:
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" ]]; then mvn -Dmaven.javadoc.skip=true clean deploy -DcloneUi=true --settings .travis-settings.xml; fi
  - if [[ "$TRAVIS_PULL_REQUEST" != "false" ]]; then mvn -Dmaven.javadoc.skip=true clean install -DcloneUi=true; fi
env:
  global:
    - secure: "I04D7jANYQZgzG5/hSffY9AkcOMaoRGysi9NdRs+FnM7u/ENJIrbtYVArwaYfrSL6kYtuRgTqmfwBH7/NvWWjGEPBH2TrSToUXXCFXMoMAKQW0qSMtmfMkrPh1peB8JbASBFAJJXU1Cy9cXMx37RGdAuTEqW07ehUsdeB0ZafiE="
    - secure: "KKwemcaeAhjU6I1u2BKUHccfQqwAF61Fm8+BwwiS/cbIGKN3/uGzu1GKrrqlg4xKci4S4jSWn+Xr+Z7yj9anT2PswvSjBZhwj4v+UJC/tv5RMvOwteeU52I+WR5gFEQwTrL8VvkerX9m1PpjroGdbjhycDVVXyjCAn1NmuuiLL8="
