CStudioAuthoring.Messages.registerBundle("siteDashboard", "kr", {
    dashboardTitle: "{0} 대시 보드",

    dashboardCollapseAll: "모든 축소",
    dashboardExpandAll: "모두 확장",
    dashboardEdit: "편집",

    approvedScheduledCollapseAll: "모든 축소",

    dashletFilterPages: "페이지",
    dashletFilterComponents: "구성 요소",
    dashletFilterDocuments: "문서",
    dashletFilterAssets: "자산",
    dashletFilterAll: "모두",

    dashletGoLiveQueueTitle: "승인을 기다리고 품목",
    dashletGoLiveCollapseAll: "모두 축소",
    dashletGoLiveExpandAll: "모두 확장",
    dashletGoLiveShowInProgress: "보기 \"진행중인 \" 항목",
    dashletGoLiveHideInProgress: "숨기기 \"진행중인 \" 항목",
    dashletGoLiveColPageName: "항목 이름",
    dashletGoLiveColEdit: "편집",
    dashletGoLiveColURL: "URL",
    dashletGoLiveColPublishDate: "날짜 및 시간 게시",
    dashletGoLiveColLastEditedBy: "마지막 편집으로",
    dashletGoLiveColLastEditedDate: "최근 편집",
    dashletGoLivePages: "페이지 ({0})",
    dashletGoLiveComponents: "구성 요소 ({0})",
    dashletGoLiveAssets: "자산 ({0})",
    dashletGoLiveEdit: "편집",

    dashletApprovedSchedTitle: "예약 된 항목을 승인",
    dashletApprovedSchedCollapseAll: "모두 축소",
    dashletApprovedSchedExpandAll: "모두 확장",
    dashletApprovedSchedShow: "쇼",
    dashletApprovedSchedColGoLiveDate: "라이브 날짜로 이동",
    dashletApprovedSchedColEdit: "편집",
    dashletApprovedSchedColURL: "URL",
    dashletApprovedSchedColLastEdited: "최근 편집",

    showNumItems: "쇼",
    dashletRecentDeployTitle: "최근 발표 된",
    dashletRecentDeployCollapseAll: "모두 축소",
    dashletRecentDeployExpandAll: "모두 확장",
    dashletRecentDeployShow: "쇼",
    dashletRecentDeployColMadeLiveDateDate: "날짜 게시",
    dashletRecentDeployColEdit: "편집",
    dashletRecentDeployColURL: "URL",
    dashletRecentDeployColEndpoint: "서버",
    dashletRecentDeployColDeployBy: "에 의해 게시",
    dashletRecentDeployColLastEdited: "최근 편집",

    dashletMyRecentActivityTitle: "내 최근 활동",
    dashletMyRecentActivityHideLiveItems: "라이브 항목 숨기기",
    dashletMyRecentActivityShowLiveItems: ", 라이브 품목",
    ddashletMyRecentActivityShow: "쇼",
    dashletMyRecentActivityColPageName: "항목 이름",
    dashletMyRecentActivityColEdit: "편집",
    dashletMyRecentActivityColURL: "URL",
    dashletMyRecentActivityColPublishDate: "날짜 게시",
    dashletMyRecentActivityColLastEditedBy: "마지막 편집으로",
    dashletMyRecentActivityColMyLastEdit: "내 마지막 편집",

    dashletIconGuideTitle: "워크 플로 아이콘 가이드",
    dashletIconGuideNavigationPage: "탐색 페이지",
    dashletIconGuideFloatingPage: "부동 페이지",
    dashletIconGuideComponent: "구성 요소",
    dashletIconGuideDocument: "문서",
    dashletIconGuideStateNew: "게시하지 마십시오",
    dashletIconGuideStateDisabled: "사용 안 함",
    dashletIconGuideStateDeleted: "삭제",
    dashletIconGuideStateInProgress: "편집",
    dashletIconGuideStateInWorkflow: "워크 플로에서",
    dashletIconGuideStateScheduled: "예약",
    dashletIconGuideStateSystemProcessing: "처리",
    dashletIconGuideStateLocked: "편집에 대해 잠김"

});

CStudioAuthoring.Messages.registerBundle("contextnav", "kr", {
    siteContent: "사이트 콘텐츠",

    wcmContentEdit: "편집",
    wcmContentView: "보기",
    wcmContentSubmit: "요청 게시",
    wcmContentDelete: "삭제",
    wcmContentSubmitDelete: "요청 삭제",
    wcmContentReject: "거부",
    wcmContentSchedule: "일정",
    wcmContentApprove: "승인 및 게시",
    wcmContentDuplicate: "중복",
    wcmContentHistory: "역사",
    wcmContentPageDisabled: "페이지를 사용할 수 없습니다 :. 배포하면, 라이브 방문자가 (404) 오류 페이지를 찾을 수 없습니다가 표시됩니다",

    InProgress: "편집",
    Deleted: "삭제",
    SubmittedforDelete: "삭제를 위해 제출",
    mixedStates: "항목 (미국 혼합)",
    Submitted: "게시를 위해 제출",
    Live: "라이브",
    Scheduled: "예약",

    search: "검색",

    logout: "로그 아웃"

});

CStudioAuthoring.Messages.registerBundle("previewTools", "kr", {
    previewToolsTitle: "미리보기 도구",
    inContextEditing: "상황에 맞는 편집",
    pageComponents: "페이지 구성 요소",
    responsivePreview: "응답 미리보기",
    desktop: "바탕 화면",
    browser: "브라우저",
    iphone: "아이폰 5 / 아이폰 5S",
    iPad: "아이 패드",
    targeting: "타겟팅",
    analytics: "웹 로그 분석",
    translation: "번역",
    inContextEditOn: "편집 컨텍스트 내에서",
    inContextEditOff: "상황에 맞는 편집 오프",
    publishingChannel: "출판 채널",
    web: "웹",
    smartPhone: "스마트 폰",
    tablet: "태블릿",
    multiVariantTesting: "멀티 변형 테스트",
    YellowVsBlue: "홈에 파란색 마스크 대 노란색",
    yellow: "황색",
    blue: "푸른",
    FacetedVsKeyword: "키워드 대면 처리 검색",
    faceted: "면 처리",
    facetedKeyword: "면 처리 + 키워드",
    keywordOnly: "키워드 만",
    HomeRedVsBlue: "블루 버튼 VS 홈 페이지 레드",
    red: "빨간",
    catalogPageSorting: "카탈로그 페이지 정렬",
    arrivalDate: "도착 일",
    priceHightoLow: "낮은 가격순 높은 가격",
    priceLowtoHigh: "높은 낮은 가격",
    editTemplate: "템플릿 편집",
    jumpToRegion: "지역로 이동",
    dimensionsPx: "크기 (PX)",
    presets: "사전",
    custom: "관습",
    addComponent: "구성 요소 추가",
    done: "완료",
    general: "일반",
    components: "구성 요소들",
    persona: "페르소나",
    properties: "등록",
    assume: "가정",
    update: "업데이트",
    active: "활동적인",
    reportsOff: "오프 보고서",
    reportsError: "오류로 인해 보고서를 렌더링 할 수 없습니다",
    addComponent :"구성 요소 추가",
    done: "완료",
    components: "구성 요소",
    general: "일반",
    text: "본문"

});

CStudioAuthoring.Messages.registerBundle("siteDropdown", "kr", {
    pages: "페이지",
    Pages: "페이지",
    page: "페이지",
    components: "구성 요소들",
    Components: "구성 요소들",
    component: "구성 요소",
    staticassets: "고정 자산",
    templates: "템플릿",
    scripts: "스크립트",
    analyticsDashboard: "웹 로그 분석 대시 보드",
    adminConsole: "관리 콘솔",
    previewSync: "미리 동기화",
    allSites: "모든 사이트",
    newContent: "새로운 내용",
    newFolder: "새 폴더",
    upload: "업로드",
    edit: "편집",
    view: "전망",
    changeTemplate: "변경 템플릿",
    delete: "삭제",
    cut: "절단",
    copy: "복사",
    paste: "풀",
    history: "역사",
    unlock: "잠금 해제",
    noActionsAvailable: "가능한 조치가 없습니다",
    createFolder: "폴더를 만들",
    createTemplate: "템플릿 만들기",
    createController: "컨트롤러 만들기",
    bulkUploadAssets: "대량 업로드 자산",
    lastEdited: "마지막 편집",
    editedBy: "에 의해 편집 됨",
    lockedBy: "에 의해 잠김",
    status: "지위",
    scheduled: "예약",
    loading: "로드...",

    /*tooltip-Status*/
    statusDeleted: "삭제",
    statusScheduledForDelete: "삭제 예정",
    statusSubmittedForDelete: "삭제를 위해 제출",
    statusAndDisabled: "및 장애인",
    statusProcessing: "처리",
    statusInProgress: "진행 중",
    statusLive: "살고있다",
    statusAnd: "과",
    statusSubmitted: "제출",
    statusScheduled: "예약",
    statusDisabled: "장애인"

});


CStudioAuthoring.Messages.registerBundle("forms", "kr", {
    expandAll: "모두 확장",
    collapseAll: "모두 축소",
    pageName: "항목 이름",
    location: "위치",
    sectionValidation: "{0}의 {1} 필드 요구 사항은 무효",
    saveAndClose: "저장 후 닫기",
    saveAndPreview: "저장 및 미리보기",
    save: "저장",
    cancel: "취소",
    close: "닫기",
    repeatAddAnother: "또 다른 추가",
    repeatMoveUp: "위로 이동",
    repeatMoveDown: "아래로 이동",
    repeatDelete: "삭제",
    errMissingRequirements: "모든 형태의 요구 사항을 만족할 때까지 당신은 저장할 수 없습니다",
    errSaveFailed: ". 형태의 컨텐츠를 저장할 수 없습니다 다시 연락처 또는 시스템 관리자 나 시도하십시오.",
    errOnRepeat: "중계기 작동에 오류 : {0}",
    errFailedToLoadContent: "오류 내용을로드 : {0}",
    errExpectedIndexXml: "이 Index.xml 이외의 파일 이름을 기대되지 않음",
    yes: "네",
    no: "아니",
    submit:"제출",
    loading:"로드&hellip;",
    viewSample: "샘플보기",
    hideSample: "숨기기 샘플",

    cancelDialogHeader:"크래프터 스튜디오",
    cancelDialogBody:"변경 사항을 저장하지 않고이 양식을 닫습니다?",

    changeTemplateDialogTitle:"경고 : 콘텐츠 형식 변경",
    changeTemplateDialogSubTitle:"크래프터 스튜디오",
    changeTemplateDialogBody:"아래의 조작은 데이터 손실이 발생할 수 있습니다. 당신은 계속 진행 하시겠습니까?",

    historyDialogTitle: "버전 기록",
    historyDialogSubTitle: "역사에 대해 표시 :",
    historyDialogTableRowVersion: "버전",
    historyDialogTableRowTime: "편집 시간",
    historyDialogTableRowEditBy: "편집",
    historyDialogTableRowComment: "논평",
    historyDialogRevert: "되돌리기",
    historyDialogLoadingWait: "로딩 중 기다려주세요&hellip;",
    historyDialogNoVersionsFound: "어떤 버전을 찾을 수 없습니다.",
    historyDialogUnable:"버전 기록을로드 할 수 없습니다.",
    historyDialogTryAgain:"다시 시도",

    deleteDialogTitle:"삭제",
    deleteDialogSubTitle:"다음 선택 항목이 삭제됩니다 :",
    deleteDialogSetLink:'이제"모든 것을 설정',
    deleteDialogPage:"페이지",
    deleteDialogDelete:"삭제",
    deleteDialogNow:"지금",
    deleteDialogFeedBack:"제출하기 전에 종속성 확인해야합니다",
    deleteDialogNoItemsSelected:"선택 항목이 없습니다",

    deleteSubmitDialogTitle:"삭제 제출",
    deleteSubmitDialogTime:"당신이 체크 된 항목을 원하는 경우 삭제할?",
    deleteSubmitEmailMe:"내 항목이 삭제 될 때 이메일을 보내주세요",
    deleteSubmitDialogAsSoon:"최대한 빨리.",

    approveDialogTitle: "게시에 대한 승인",
    approveDialogSubTitle: "다음 선택 항목이 게재됩니다.",
    approveDialogPage: "페이지",
    approveDialogOriginalSchedule: "원래 일정",
    approveDialogSubmissionComment: "제출 코멘트",
    approveDialogSelectedScheduling: "선택 항목 예약",
    approveDialogItemsLiveNow: "항목은 지금 살아 가야한다.",
    approveDialogItemsLiveDate: "항목은 특정 날짜와 시간에 게재",
    approveDialogPublishContent: "콘텐츠를 게시",
    approveDialogPublishingOptions: "출판 옵션",
    approveDialogBroadcastUpdate: "방송 콘텐츠 업데이트",

    requestApproveDialogTitle: "게시를 요청할",
    requestApproveDialogSubTitle: "당신이 원하는 때 체크 항목 (들)을 게재하는 방법?",
    requestApproveDialogEmailMe: "항목 살아 갈 때 이메일을 보내주세요.",

    newContTypeDialogTitle: "콘텐츠 형식 만들기",
    newContTypeDialogDisplayLabel: "표시 라벨",
    newContTypeDialogContentTypeName: "콘텐츠 형식 이름",
    newContTypeDialogType: "유형",
    newContTypeDialogPage: "페이지",
    component: "구성 요소",
    newContTypeDialogLabelMsg: "이 콘텐츠 유형 표시 라벨을 제공",
    newContTypeDialogContentTypeNamelMsg: "이 콘텐츠 유형에 대한 시스템 이름을 입력합니다",
    newContTypeDialogTypeMsg: "이 콘텐츠 유형에 대한 유형을 선택",

    adminHelpDialogTitle: "필드 내용",

    adminKeyValDialogTitle: "값",
    adminKeyValDialogKey: "키",
    adminKeyValDialogValue: "값",
    addAnother: "또 다른 추가",

    supportedChannelsDialogLabel: "상표",
    supportedChannelsDialogName: "이름",
    supportedChannelsDialogSize :"크기",

    setStatedDialogTitle: "국가를 선택하십시오",
    setStatedDialogSetStates: "설정 미국",
    setStatedDialogSystemProcessing: "시스템 처리",

    currentPage: "현재 페이지"

});

CStudioAuthoring.Messages.registerBundle("search", "kr", {
    defaultTitle: "수색 WCM",
    searchButtonLabel: "수색",
    keywordsLabel: "키워드 (선택)",
    searchResults: "검색 결과",
    showing: "(보기 {0}-{1} 의 {2})",
    hideDescriptions: "숨기기 설명",
    showDescriptions: "보기 설명",
    show: "표시",
    sort: "종류",
    sortRelevance: "관련성",
    sortAlphabetical: "알파벳",
    sortCreateDate: "날짜 만들기",
    pagePrevious: "이전",
    pageNext: "다음",
    resultsEdited: "편집",
    resultsBy: "편집",
    resultsUnknownType: "알 수없는 유형",
    resultsTemplate: "주형",
    errSearchFailed: "검색하지 못했습니다. 필터를 조정 해보십시오. 원인 : 문제가 오류와 함께 연락처 관리자 지속되면: {0}",
    errNoResults: "귀하의 검색 결과가 없습니다."
});

CStudioAuthoring.Messages.registerBundle("contentTypes", "kr", {
    contentTypes: "콘텐츠 형식",
    configuration: "구성",
    workflowJobs: "워크 플로 작업",
    workflowStates: "워크 플로우 미국",
    loggingLevels: "로깅 수준",
    logConsole: "로그인 콘솔",
    label: "콘텐츠 형식",
    openExistingType: "열기 기존 유형",
    createNewType: "새로운 유형 만들기",
    save: "저장",
    saved: "저장",
    saveFailed: "저장 실패",
    formSection: "양식 섹션",
    repeatingGroup: "반복 그룹",
    minOccurs: "최소 발생 수",
    maxOccurs: "최대 발생 수",
    formBasics: "양식 기본 사항",
    formTitle: "이름",
    description: "기술",
    objectType: "개체 유형",
    contentType: "컨텐츠 유형",
    datasourceBasics: "데이터 소스 기본 사항",
    title: "이름",
    name: "이름",
    properties: "등록",
    sectionBasics: "섹션 기본 사항",
    variableName: "이름 / 변수 이름",
    iceGroup: "ICE 그룹",
    fieldBasics: "필드의 기본 사항",
    defaultValue: "기본값",
    help: "도와주세요",
    constraints: "제약",
    propertiesExplorer: "등록 탐색기",
    controls: "컨트롤",
    datasources: "데이터 소스",
    defaultOpen: "기본 열기",
    showInNav: "탐색에 표시",
    descriptorMapper: "매퍼",

    /*Controls*/
    textArea: "텍스트 영역",
    richTextEditor: "서식있는 텍스트 편집기s",
    input: "입력",
    dropdown: "쓰러지 다",
    dateTime: "날짜 시간",
    checkBox: "확인란",
    groupedCheckboxes: "그룹화 확인란",
    itemSelector: "항목 선택기",
    image: "영상",
    video: "비디오",
    label: "상표",
    pageOrder: "페이지 순서",
    fileName: "파일 이름",
    autoFilename: "자동 파일 이름",
    forceHTTPS: "포스 HTTPS",
    disabled: "장애인",
    flash: "플래시",
    internalName: "내부 이름",

    /*Datasources */
    childContent: "자식 내용",
    imageUploadedDesktop: "이미지 바탕 화면에서 업로드",
    DAMImage: "DAM 이미지 플리커 (Flickr)",
    fileUploadedDesktop: "파일 바탕 화면에서 업로드",
    flashUploadedDesktop: "플래시 바탕 화면에서 업로드",
    videoUploadedDesktop: "비디오 바탕 화면에서 업로드",
    staticKeyValuePairs: "정적 키 값 쌍",
    configuredListOfPairs: "쌍의 구성 목록",
    fileBrowse: "찾아보기를 파일",
    hubspotForms: "허브 스팟 양식",
    imageFromRepository: "저장소에서 이미지",
    salesforceCampaigns: "세일즈 포스 캠페인",
    treeContent: "트리 내용",

    /*Properties*/
    Size: "크기",
    maxLength: "최대 길이s",
    width: "폭",
    height: "신장",
    allowResize: "크기 조정 허용",
    forceRootBlockP: "강제 루트 블록 p 태그",
    forcePNewLines: "강제 p는 신규 라인 태그",
    forceBRNewLines: "포스 카에 새로운 라인",
    requireImageAlt: "이미지 Alt 키 태그를 필요",
    supportedChannels: "지원 채널",
    RTEConfiguration: "RTE 구성",
    imageManager: "이미지 관리자",
    showDate: "쇼 날짜",
    showTime: "쇼 타임",
    setNowLink: "이제 링크 설정",
    populated: "인구",
    allowPastDate: "과거 날짜 허용",
    readonly: "읽기 전용",
    readonlyOnEdit: "편집에 읽기 전용",
    datasource: "데이터 소스",
    showSelectAll: '쇼는 "모두 선택"',
    allowEmptyValue: "빈 값을 허용",
    thumbnailWidth: "미리보기 폭",
    thumbnailHeight: "미리보기 높이",
    displaySize: "디스플레이 크기",
    text: "본문",
    minSize: "최소 크기",
    maxSize: "최대 크기",
    itemManager: "항목 관리자",
    disableFlatteningSearch: "검색 편평 해제",
    singleValueFilename: "단일 값의 파일 이름을 사용 (이전 버전과 호환)",
    columns: "열",
    rows: "행",
    dataType: "데이터 형식",
    listName: "목록 이름",
    repositoryPath: "저장소 경로",
    string: "현",
    integer: "정수",
    float: "플로트",
    date: "날짜",
    HTML: "HTML",
    options: "옵션",
    showKeys: "보기 키 (항목 전용)",
    taxonomyName: "분류 이름",
    defaultType: "기본 유형",
    displayTemplate: "디스플레이 템플릿",
    mergeStrategy: "전략을 병합",

    /*Restrictions*/
    required: "필요",
    minimumSelection: "최소 선택",
    matchPattern: "경기 패턴",
    allowDuplicate: "중복 허용",

    /*Values*/
    noDatasources: "이 컨트롤에 사용 가능한 데이터 소스가 없습니다",
    editMessage: "편집 메시지",
    setMessage: "설정 메시지",

    /*States Workflow*/
    setStatedTabID: "ID",
    setStatedTabState: "상태x",
    setStatedTabSystemProcessing: "시스템 처리",
    setStatedTabSelectAll: "모두 선택",
    false: "그릇된",
    true: "참된",

    /*Jobs Workflow*/
    jobWorkflowTabAct: "행위",
    jobWorkflowTabJobID: "작업 확인",
    jobWorkflowTabProcessName: "프로세스 이름",
    jobWorkflowTabCreatedDate: "만든 날짜",
    jobWorkflowTabModifiedDate: "수정 한 날짜",
    jobWorkflowTabSiteId: "사이트 아이디",
    jobWorkflowTabItemsInJob: "작업의 항목",
    jobWorkflowTabProperties: "등록",
    jobWorkflowTabStatus: "지위",

    /*Loggin Levels*/
    logginLevelsTabLogger: "로거",
    logginLevelsTabCurrentLevel: "현재 수준",
    logginLevelsTabChangeLevel: "변경 수준",
    debug: "디버그",
    warn: "경고",
    info: "정보",
    error: "오류",

    /*Configuration*/
    confTabSelectConf: "구성을 선택합니다",
    confTabConfigurations: "구성",
    confTabConfDesc: "구성의 목록을 정의합니다",
    confTabAdminTools: "관리 도구",
    confTabAdminToolsDesc: "관리 툴의리스트가 정의 가능한",
    confTabAnalyticsDashboardConf: "웹 로그 분석 대시 보드 구성",
    confTabAnalyticsDashboardConfDesc: "보고서의 유형 분석 대시 보드에 표시를 정의",
    confTabAnalyticsPreviewConf: "웹 로그 분석 미리 구성",
    confTabAnalyticsReportConf: "웹 로그 분석 구성 보고서",
    confTabContextualNavigationConf: "콘텐츠 탐색 구성",
    confTabContextualNavigationConfDesc: "사이트 콘텐츠의 탐색 모음에서 모듈을 정의합니다",
    confTabSiteDropdownConf: "사이트 구성 드롭 다운",
    confTabSiteDropdownConfDesc: "사이트 드롭 다운 표시 줄에 모듈을 정의합니다",
    confTabEndpointsConf: "엔드 포인트 구성",
    confTabEndpointsConfDesc: "엔드 포인트의리스트가 정의 가능한",
    confTabDevEnvironmentConf: "데브 환경 구성",
    confTabDevEnvironmentConfDesc: "개발 환경의 구성을 정의",
    confTabTargetsConf: "대상 구성",
    confTabTargetsConfDesc: "대상 목록 양식 데이터 소스에 사용되는 정의합니다",
    confTabRTEConf: "RTE 구성",
    confTabRTEConfDesc: "서식있는 텍스트 편집기는 형태로 구성을 정의",
    confTabPreviewAssetConf: "자산 미리 구성",
    confTabPreviewAssetConfDesc: "XML 컨텐츠와 연관된 편집 자산 목록을 정의",
    confTabPreviewComponentsConf: "구성 요소 구성 미리보기",
    confTabPreviewComponentsConfDesc: "프리뷰를 동적으로 생성 할 수있는 구성 요소의 목록을 정의",
    confTabPreviewPanelConf: "미리보기 패널 구성",
    confTabconfTabPreviewPanelConfDesc: "미리보기에서 사용할 수있는 도구의 목록을 정의",
    confTabPersonasConf: "사람 구성",
    confTabPersonasConfDesc: "사람들은 미리보기에서 가정 할 수 사람들의 목록을 정의합니다",
    confTabNotificationConf: "알림 구성",
    confTabNotificationConfDesc: "UI 메시지의 목록을 정의",
    confTabPermissionsMappings: "권한 매핑",
    confTabPermissionsMappingsDesc: "권한 및 경로 맵을 정의",
    confTabRoleMappings: "역할 매핑",
    confTabRoleMappingsDesc: "사이트에서 사용할 수있는 역할의 목록을 정의합니다",
    confTabSiteConf: "사이트 구성",
    confTabSiteConfDesc: "일반 사이트 구성을 정의",
    confTabWorkflowConf: "워크 플로우 구성",
    confTabWorkflowConfDesc: "시스템에서 사용할 수있는 워크 플로우를 정의",

    /* Errors */
    errorTitle: ". 필드와 데이터 소스에 대한 모든 제목을 입력 해주세요.",
    errorName: ". 대한 변수 이름을 기입하십시오: "
});