CStudioAuthoring.Messages.registerBundle("siteDashboard", "kr", {
    dashboardTitle: "{0} 대시 보드",

    dashboardCollapseAll: "모든 축소",
    dashboardExpandAll: "모두 확장",
    dashboardEdit: "편집",

    approvedScheduledCollapseAll: "모든 축소",

    dashletFilterPages: "페이지",
    dashletFilterComponents: "구성 요소",
    dashletFilterDocuments: "문서",
    dashletFilterAssets: "자산",
    dashletFilterAll: "모두",

    dashletGoLiveQueueTitle: "승인을 기다리고 품목",
    dashletGoLiveCollapseAll: "모두 축소",
    dashletGoLiveExpandAll: "모두 확장",
    dashletGoLiveShowInProgress: "보기 \"진행중인 \" 항목",
    dashletGoLiveHideInProgress: "숨기기 \"진행중인 \" 항목",
    dashletGoLiveColPageName: "항목 이름",
    dashletGoLiveColEdit: "편집",
    dashletGoLiveColURL: "URL",
    dashletGoLiveColPublishDate: "날짜 및 시간 게시",
    dashletGoLiveColLastEditedBy: "마지막 편집으로",
    dashletGoLiveColLastEditedDate: "최근 편집",
    dashletGoLivePages: "페이지 ({0})",
    dashletGoLiveComponents: "구성 요소 ({0})",
    dashletGoLiveAssets: "자산 ({0})",
    dashletGoLiveEdit: "편집",

    dashletApprovedSchedTitle: "예약 된 항목을 승인",
    dashletApprovedSchedCollapseAll: "모두 축소",
    dashletApprovedSchedExpandAll: "모두 확장",
    dashletApprovedSchedShow: "쇼",
    dashletApprovedSchedColGoLiveDate: "라이브 날짜로 이동",
    dashletApprovedSchedColEdit: "편집",
    dashletApprovedSchedColURL: "URL",
    dashletApprovedSchedColLastEdited: "최근 편집",

    showNumItems: "쇼",
    dashletRecentDeployTitle: "최근 발표 된",
    dashletRecentDeployCollapseAll: "모두 축소",
    dashletRecentDeployExpandAll: "모두 확장",
    dashletRecentDeployShow: "쇼",
    dashletRecentDeployColMadeLiveDateDate: "날짜 게시",
    dashletRecentDeployColEdit: "편집",
    dashletRecentDeployColURL: "URL",
    dashletRecentDeployColEndpoint: "서버",
    dashletRecentDeployColDeployBy: "에 의해 게시",

    dashletMyRecentActivityTitle: "내 최근 활동",
    dashletMyRecentActivityHideLiveItems: "라이브 항목 숨기기",
    dashletMyRecentActivityShowLiveItems: ", 라이브 품목",
    ddashletMyRecentActivityShow: "쇼",
    dashletMyRecentActivityColPageName: "항목 이름",
    dashletMyRecentActivityColEdit: "편집",
    dashletMyRecentActivityColURL: "URL",
    dashletMyRecentActivityColPublishDate: "날짜 게시",
    dashletMyRecentActivityColLastEditedBy: "마지막 편집으로",
    dashletMyRecentActivityColMyLastEdit: "내 마지막 편집",

    dashletIconGuideTitle: "워크 플로 아이콘 가이드",
    dashletIconGuideNavigationPage: "탐색 페이지",
    dashletIconGuideFloatingPage: "부동 페이지",
    dashletIconGuideComponent: "구성 요소",
    dashletIconGuideDocument: "문서",
    dashletIconGuideStateNew: "게시하지 마십시오",
    dashletIconGuideStateDisabled: "사용 안 함",
    dashletIconGuideStateDeleted: "삭제",
    dashletIconGuideStateInProgress: "편집",
    dashletIconGuideStateInWorkflow: "워크 플로에서",
    dashletIconGuideStateScheduled: "예약",
    dashletIconGuideStateSystemProcessing: "처리",
    dashletIconGuideStateLocked: "편집에 대해 잠김"

});

CStudioAuthoring.Messages.registerBundle("contextnav", "kr", {
    siteContent: "사이트 콘텐츠",

    wcmContentEdit: "편집",
    wcmContentView: "보기",
    wcmContentSubmit: "요청 게시",
    wcmContentDelete: "삭제",
    wcmContentSubmitDelete: "요청 삭제",
    wcmContentReject: "거부",
    wcmContentSchedule: "일정",
    wcmContentApprove: "승인 및 게시",
    wcmContentDuplicate: "중복",
    wcmContentHistory: "역사",
    wcmContentPageDisabled: "페이지를 사용할 수 없습니다 :. 배포하면, 라이브 방문자가 (404) 오류 페이지를 찾을 수 없습니다가 표시됩니다",

    InProgress: "편집",
    Deleted: "삭제",
    SubmittedforDelete: "삭제를 위해 제출",
    mixedStates: "항목 (미국 혼합)",
    Submitted: "게시를 위해 제출",
    Live: "라이브",
    Scheduled: "예약",

    search: "검색",

    logout: "로그 아웃"

});

CStudioAuthoring.Messages.registerBundle("previewTools", "kr", {
    previewToolsTitle: "미리보기 도구",
    inContextEditing: "상황에 맞는 편집",
    pageComponents: "페이지 구성 요소",
    responsivePreview: "응답 미리보기",
    desktop: "바탕 화면",
    browser: "브라우저",
    iphone: "아이폰 5 / 아이폰 5S",
    iPad: "아이 패드",
    targeting: "타겟팅",
    analytics: "웹 로그 분석",
    translation: "번역",
    inContextEditOn: "편집 컨텍스트 내에서",
    inContextEditOff: "상황에 맞는 편집 오프",
    publishingChannel: "출판 채널",
    web: "웹",
    smartPhone: "스마트 폰",
    tablet: "태블릿",
    multiVariantTesting: "멀티 변형 테스트",
    YellowVsBlue: "홈에 파란색 마스크 대 노란색",
    yellow: "황색",
    blue: "푸른",
    FacetedVsKeyword: "키워드 대면 처리 검색",
    faceted: "면 처리",
    facetedKeyword: "면 처리 + 키워드",
    keywordOnly: "키워드 만",
    HomeRedVsBlue: "블루 버튼 VS 홈 페이지 레드",
    red: "빨간",
    catalogPageSorting: "카탈로그 페이지 정렬",
    arrivalDate: "도착 일",
    priceHightoLow: "낮은 가격순 높은 가격",
    priceLowtoHigh: "높은 낮은 가격",
    editTemplate: "템플릿 편집",
    jumpToRegion: "지역로 이동",
    dimensionsPx: "크기 (PX)",
    presets: "사전",
    custom: "관습",
    addComponent: "구성 요소 추가",
    done: "완료",
    general: "일반",
    components: "구성 요소들",
    persona: "페르소나",
    properties: "등록",
    assume: "가정",
    update: "업데이트",
    active: "활동적인",
    reportsOff: "오프 보고서",
    reportsError: "오류로 인해 보고서를 렌더링 할 수 없습니다",
    addComponent :"구성 요소 추가",
    done: "완료",
    components: "구성 요소",
    general: "일반",
    text: "본문"

});

CStudioAuthoring.Messages.registerBundle("siteDropdown", "kr", {
    pages: "페이지",
    page: "페이지",
    components: "구성 요소들",
    component: "구성 요소",
    staticassets: "고정 자산",
    templates: "템플릿",
    scripts: "스크립트",
    analyticsDashboard: "웹 로그 분석 대시 보드",
    adminConsole: "관리 콘솔",
    previewSync: "미리 동기화",
    allSites: "모든 사이트",
    newContent: "새로운 내용",
    newFolder: "새 폴더",
    upload: "업로드",
    edit: "편집",
    view: "전망",
    changeTemplate: "변경 템플릿",
    delete: "삭제",
    cut: "절단",
    copy: "복사",
    paste: "풀",
    history: "역사",
    unlock: "잠금 해제",
    noActionsAvailable: "가능한 조치가 없습니다",
    createFolder: "폴더를 만들",
    createTemplate: "템플릿 만들기",
    createController: "컨트롤러 만들기",
    bulkUploadAssets: "대량 업로드 자산",
    lastEdited: "마지막 편집",
    editedBy: "에 의해 편집 됨",
    lockedBy: "에 의해 잠김",
    status: "지위",
    scheduled: "예약",
    loading: "로드...",

    /*tooltip-Status*/
    statusDeleted: "삭제",
    statusScheduledForDelete: "삭제 예정",
    statusSubmittedForDelete: "삭제를 위해 제출",
    statusAndDisabled: "및 장애인",
    statusProcessing: "처리",
    statusInProgress: "진행 중",
    statusLive: "살고있다",
    statusAnd: "과",
    statusSubmitted: "제출",
    statusScheduled: "예약",
    statusDisabled: "장애인"

});


CStudioAuthoring.Messages.registerBundle("forms", "kr", {
    expandAll: "모두 확장",
    collapseAll: "모두 축소",
    pageName: "항목 이름",
    location: "위치",
    sectionValidation: "{0}의 {1} 필드 요구 사항은 무효",
    saveAndClose: "저장 후 닫기",
    saveAndPreview: "저장 및 미리보기",
    cancel: "취소",
    close: "닫기",
    repeatAddAnother: "또 다른 추가",
    repeatMoveUp: "위로 이동",
    repeatMoveDown: "아래로 이동",
    repeatDelete: "삭제",
    errMissingRequirements: "모든 형태의 요구 사항을 만족할 때까지 당신은 저장할 수 없습니다",
    errSaveFailed: ". 형태의 컨텐츠를 저장할 수 없습니다 다시 연락처 또는 시스템 관리자 나 시도하십시오.",
    errOnRepeat: "중계기 작동에 오류 : {0}",
    errFailedToLoadContent: "오류 내용을로드 : {0}",
    errExpectedIndexXml: "이 Index.xml 이외의 파일 이름을 기대되지 않음",
    yes: "네",
    no: "아니",
    submit:"제출",
    loading:"로드&hellip;",

    cancelDialogHeader:"크래프터 스튜디오",
    cancelDialogBody:"변경 사항을 저장하지 않고이 양식을 닫습니다?",

    changeTemplateDialogTitle:"경고 : 콘텐츠 형식 변경",
    changeTemplateDialogSubTitle:"크래프터 스튜디오",
    changeTemplateDialogBody:"아래의 조작은 데이터 손실이 발생할 수 있습니다. 당신은 계속 진행 하시겠습니까?",

    historyDialogTitle: "버전 기록",
    historyDialogSubTitle: "역사에 대해 표시 :",
    historyDialogTableRowVersion: "버전",
    historyDialogTableRowTime: "편집 시간",
    historyDialogTableRowEditBy: "편집",
    historyDialogTableRowComment: "논평",
    historyDialogRevert: "되돌리기",
    historyDialogLoadingWait: "로딩 중 기다려주세요&hellip;",
    historyDialogNoVersionsFound: "어떤 버전을 찾을 수 없습니다.",
    historyDialogUnable:"버전 기록을로드 할 수 없습니다.",
    historyDialogTryAgain:"다시 시도",

    deleteDialogTitle:"삭제",
    deleteDialogSubTitle:"다음 선택 항목이 삭제됩니다 :",
    deleteDialogSetLink:'이제"모든 것을 설정',
    deleteDialogPage:"페이지",
    deleteDialogDelete:"삭제",
    deleteDialogNow:"지금",
    deleteDialogFeedBack:"제출하기 전에 종속성 확인해야합니다",
    deleteDialogNoItemsSelected:"선택 항목이 없습니다",

    deleteSubmitDialogTitle:"삭제 제출",
    deleteSubmitDialogTime:"당신이 체크 된 항목을 원하는 경우 삭제할?",
    deleteSubmitEmailMe:"내 항목이 삭제 될 때 이메일을 보내주세요",
    deleteSubmitDialogAsSoon:"최대한 빨리.",

    approveDialogTitle: "게시에 대한 승인",
    approveDialogSubTitle: "다음 선택 항목이 게재됩니다.",
    approveDialogPage: "페이지",
    approveDialogOriginalSchedule: "원래 일정",
    approveDialogSubmissionComment: "제출 코멘트",
    approveDialogSelectedScheduling: "선택 항목 예약",
    approveDialogItemsLiveNow: "항목은 지금 살아 가야한다.",
    approveDialogItemsLiveDate: "항목은 특정 날짜와 시간에 게재",
    approveDialogPublishContent: "콘텐츠를 게시",
    approveDialogPublishingOptions: "출판 옵션",
    approveDialogBroadcastUpdate: "방송 콘텐츠 업데이트",

    requestApproveDialogTitle: "게시를 요청할",
    requestApproveDialogSubTitle: "당신이 원하는 때 체크 항목 (들)을 게재하는 방법?",
    requestApproveDialogEmailMe: "항목 살아 갈 때 이메일을 보내주세요."

});

CStudioAuthoring.Messages.registerBundle("search", "kr", {
    defaultTitle: "수색 WCM",
    searchButtonLabel: "수색",
    keywordsLabel: "키워드 (선택)",
    searchResults: "검색 결과",
    showing: "(보기 {0}-{1} 의 {2})",
    hideDescriptions: "숨기기 설명",
    showDescriptions: "보기 설명",
    show: "표시",
    sort: "종류",
    sortRelevance: "관련성",
    sortAlphabetical: "알파벳",
    sortCreateDate: "날짜 만들기",
    pagePrevious: "이전",
    pageNext: "다음",
    resultsEdited: "편집",
    resultsBy: "편집",
    resultsUnknownType: "알 수없는 유형",
    resultsTemplate: "주형",
    errSearchFailed: "검색하지 못했습니다. 필터를 조정 해보십시오. 원인 : 문제가 오류와 함께 연락처 관리자 지속되면: {0}",
    errNoResults: "귀하의 검색 결과가 없습니다."
});

CStudioAuthoring.Messages.registerBundle("contentTypes", "kr", {
    label: "Content Types",
    openExistingType: "Open Existing Type",
    createNewType: "Create New Type",
    save: "Save",
    saved: "Saved",
    saveFailed: "Save Failed",
    formSection: "Form Section",
    repeatingGroup: "Repeating Group",
    minOccurs: "Minimum Occurances",
    maxOccurs: "Maximum Occurances",
    formBasics: "Form Basics",
    formTitle: "title",
    description: "Description",
    objectType: "Object Type",
    contentType: "Content Type",
    datasourceBasics: "Data Source Basics",
    title: "Title",
    name: "Name",
    properties: "Properties",
    sectionBasics: "Section Basics",
    variableName: "Name / Variable Name",
    iceGroup: "ICE Group",
    fieldBasics: "Field Basics",
    defaultValue: "Default Value",
    help: "Help",
    properties: "Properties",
    constraints: "Constraints",
    propertiesExplorer: "Properties Explorer",
    controls: "Controls",
    datasources: "Data Sources"
});