CStudioAuthoring.Messages.registerBundle ( "siteDashboard", "kr",
     {dashboardTitle : "{0} 대시 보드",
  
       dashletFilterPages : "페이지",
       dashletFilterComponents : "구성 요소",
       dashletFilterDocuments : "문서",
       dashletFilterAssets: "자산",
       dashletFilterAll : "모두",

       dashletGoLiveQueueTitle : "승인을 기다리고 품목",
       dashletGoLiveCollapseAll : "모두 축소",
       dashletGoLiveExpandAll : "모두 확장",
       dashletGoLiveShowInProgress : "보기 \"진행중인 \" 항목",
       dashletGoLiveHideInProgress:"숨기기 \"진행중인 \" 항목",
       dashletGoLiveColPageName : "항목 이름",
       dashletGoLiveColEdit : "편집",
       dashletGoLiveColURL : "URL",
       dashletGoLiveColPublishDate : "날짜 및 시간 게시",
       dashletGoLiveColLastEditedBy : "마지막 편집으로",
       dashletGoLiveColLastEditedDate : "최근 편집",
       dashletGoLivePages : "페이지 ({0})",
       dashletGoLiveComponents : "구성 요소 ({0})",
       dashletGoLiveAssets: "자산 ({0})",
       dashletGoLiveEdit : "편집",

       dashletApprovedSchedTitle: "예약 된 항목을 승인",
       dashletApprovedSchedCollapseAll : "모두 축소",
       dashletApprovedSchedExpandAll : "모두 확장",
       dashletApprovedSchedShow : "쇼",
       dashletApprovedSchedColGoLiveDate : "라이브 날짜로 이동",
       dashletApprovedSchedColEdit : "편집",
       dashletApprovedSchedColURL : "URL",
       dashletApprovedSchedColLastEdited : "최근 편집",

       dashletRecentDeployTitle: "최근 발표 된",
       dashletRecentDeployCollapseAll : "모두 축소",
       dashletRecentDeployExpandAll : "모두 확장",
       dashletRecentDeployShow : "쇼",
       dashletRecentDeployColMadeLiveDateDate : "날짜 게시",
       dashletRecentDeployColEdit : "편집",
       dashletRecentDeployColURL : "URL",
       dashletRecentDeployColEndpoint : "서버",
       dashletRecentDeployColDeployBy: "에 의해 게시",

       dashletMyRecentActivityTitle : "내 최근 활동",
       dashletMyRecentActivityHideLiveItems : "라이브 항목 숨기기",
       dashletMyRecentActivityShowLiveItems: ", 라이브 품목",
       ddashletMyRecentActivityShow : "쇼",
       dashletMyRecentActivityColPageName : "항목 이름",
       dashletMyRecentActivityColEdit : "편집",
       dashletMyRecentActivityColURL : "URL",
       dashletMyRecentActivityColPublishDate : "날짜 게시",
       dashletMyRecentActivityColLastEditedBy : "마지막 편집으로",
       dashletMyRecentActivityColMyLastEdit : "내 마지막 편집",

       dashletIconGuideTitle : "워크 플로 아이콘 가이드",
       dashletIconGuideNavigationPage : "탐색 페이지",
       dashletIconGuideFloatingPage : "부동 페이지",
       dashletIconGuideComponent : "구성 요소",
       dashletIconGuideDocument : "문서",
       dashletIconGuideStateNew: "게시하지 마십시오",
       dashletIconGuideStateDisabled : "사용 안 함",
       dashletIconGuideStateDeleted : "삭제",
       dashletIconGuideStateInProgress : "편집",
       dashletIconGuideStateInWorkflow : "워크 플로에서",
       dashletIconGuideStateScheduled : "예약",
       dashletIconGuideStateSystemProcessing : "처리",
       dashletIconGuideStateLocked : "편집에 대해 잠김",

});

CStudioAuthoring.Messages.registerBundle ( "contextnav", "kr", {
       siteContent : "사이트 콘텐츠",

       wcmContentEdit : "편집",
       wcmContentView : "보기",
       wcmContentSubmit : "요청 게시",
       wcmContentDelete : "삭제",
       wcmContentSubmitDelete : "요청 삭제",
       wcmContentReject: "거부",
       wcmContentSchedule : "일정",
       wcmContentApprove : "승인 및 게시",
       wcmContentDuplicate : "중복",
       wcmContentHistory : "역사",
       wcmContentPageDisabled : "페이지를 사용할 수 없습니다 :. 배포하면, 라이브 방문자가 (404) 오류 페이지를 찾을 수 없습니다가 표시됩니다",
      
       InProgress: "편집",
       Deleted: "삭제",
       SubmittedforDelete: "삭제를 위해 제출",
       mixedStates : "항목 (미국 혼합)",
       Submitted: "게시를 위해 제출",
       Live: "라이브",
       Scheduled: "예약",

       search: "검색",

       logout: "로그 아웃",

});

CStudioAuthoring.Messages.registerBundle ( "forms", "kr", {
       expandAll : "모두 확장",
       collapseAll : "모두 축소",
       pageName : "항목 이름",
       location : "위치",
       sectionValidation : "{0}의 {1} 필드 요구 사항은 무효",
       saveAndClose : "저장 후 닫기",
       saveAndPreview : "저장 및 미리보기",
       cancel : "취소",
       close : "닫기",
       repeatAddAnother : "또 다른 추가",
       repeatMoveUp : "위로 이동",
       repeatMoveDown : "아래로 이동",
       repeatDelete : "삭제",
       errMissingRequirements: "모든 형태의 요구 사항을 만족할 때까지 당신은 저장할 수 없습니다",
       errSaveFailed: ". 형태의 컨텐츠를 저장할 수 없습니다 다시 연락처 또는 시스템 관리자 나 시도하십시오.",
       errOnRepeat: "중계기 작동에 오류 : {0}",
       errFailedToLoadContent : "오류 내용을로드 : {0}",
       errExpectedIndexXml : "이 Index.xml 이외의 파일 이름을 기대되지 않음",
      

});