ALTER TABLE CSTUDIO_OBJECTMETADATA ADD COLUMN SUBMISSIONCOMMENT VARCHAR(2000);

ALTER TABLE CSTUDIO_OBJECTMETADATA ADD COLUMN LAUNCHDATE DATE;

ALTER TABLE CSTUDIO_OBJECTMETADATA ADD CONSTRAINT OM_SITE_PATH_UNIQUE UNIQUE (SITE, PATH) ;

ALTER TABLE CSTUDIO_OBJECTSTATE ADD CONSTRAINT OS_SITE_PATH_UNIQUE UNIQUE (SITE, PATH);
