ALTER TABLE CSTUDIO_OBJECTMETADATA ADD COLUMN SUBMISSIONCOMMENT VARCHAR(2000);

ALTER TABLE CSTUDIO_OBJECTMETADATA ADD COLUMN MODIFIED_NEW TIMESTAMP;
UPDATE CSTUDIO_OBJECTMETADATA SET MODIFIED_NEW = TIMESTAMP(MODIFIED,'12:00:00');
ALTER TABLE CSTUDIO_OBJECTMETADATA DROP COLUMN MODIFIED;
RENAME COLUMN CSTUDIO_OBJECTMETADATA.MODIFIED_NEW TO MODIFIED;

ALTER TABLE CSTUDIO_OBJECTMETADATA ADD COLUMN LAUNCHDATE_NEW TIMESTAMP;
UPDATE CSTUDIO_OBJECTMETADATA SET LAUNCHDATE_NEW = TIMESTAMP(LAUNCHDATE,'12:00:00');
ALTER TABLE CSTUDIO_OBJECTMETADATA DROP COLUMN LAUNCHDATE;
RENAME COLUMN CSTUDIO_OBJECTMETADATA.LAUNCHDATE_NEW TO LAUNCHDATE;

ALTER TABLE CSTUDIO_OBJECTMETADATA ADD CONSTRAINT OM_SITE_PATH_UNIQUE UNIQUE (SITE, PATH) ;

ALTER TABLE CSTUDIO_OBJECTSTATE ADD CONSTRAINT OS_SITE_PATH_UNIQUE UNIQUE (SITE, PATH);

ALTER TABLE CSTUDIO_ACTIVITY ADD COLUMN MODIFIED_DATE_NEW TIMESTAMP;
UPDATE CSTUDIO_ACTIVITY SET MODIFIED_DATE_NEW = TIMESTAMP(MODIFIED_DATE,'12:00:00');
ALTER TABLE CSTUDIO_ACTIVITY DROP COLUMN MODIFIED_DATE;
RENAME COLUMN CSTUDIO_ACTIVITY.MODIFIED_DATE_NEW TO MODIFIED_DATE;

ALTER TABLE CSTUDIO_ACTIVITY ADD COLUMN CREATION_DATE_NEW TIMESTAMP;
UPDATE CSTUDIO_ACTIVITY SET CREATION_DATE_NEW = TIMESTAMP(CREATION_DATE,'12:00:00');
ALTER TABLE CSTUDIO_ACTIVITY DROP COLUMN CREATION_DATE;
RENAME COLUMN CSTUDIO_ACTIVITY.CREATION_DATE_NEW TO CREATION_DATE;

ALTER TABLE CSTUDIO_COPYTOENVIRONMENT ADD COLUMN SCHEDULEDDATE_NEW TIMESTAMP;
UPDATE CSTUDIO_COPYTOENVIRONMENT SET SCHEDULEDDATE_NEW = TIMESTAMP(SCHEDULEDDATE,'12:00:00');
ALTER TABLE CSTUDIO_COPYTOENVIRONMENT DROP COLUMN SCHEDULEDDATE;
RENAME COLUMN CSTUDIO_COPYTOENVIRONMENT.SCHEDULEDDATE_NEW TO SCHEDULEDDATE;

ALTER TABLE CSTUDIO_DEPLOYMENTSYNCHISTORY ADD COLUMN SYNCDATE_NEW TIMESTAMP;
UPDATE CSTUDIO_DEPLOYMENTSYNCHISTORY SET SYNCDATE_NEW = TIMESTAMP(SYNCDATE,'12:00:00');
ALTER TABLE CSTUDIO_DEPLOYMENTSYNCHISTORY DROP COLUMN SYNCDATE;
RENAME COLUMN CSTUDIO_DEPLOYMENTSYNCHISTORY.SYNCDATE_NEW TO SYNCDATE;