
CStudioAuthoring.Messages.registerBundle("siteDashboard", "sr",
    { dashboardTitle: "{0} Komandna Tabla",
  
      dashletFilterPages: "Strane",
      dashletFilterComponents: "Komponente",
      dashletFilterDocuments: "Dokumenta",
      dashletFilterAssets: "Aktiva",
      dashletFilterAll: "Sve",

      dashletGoLiveQueueTitle: "Stavke koje čekaju na odobrenje",
      dashletGoLiveCollapseAll: "Sklopiti sve",
      dashletGoLiveExpandAll: "Raširiti sve",
      dashletGoLiveShowInProgress: "Show \"In-Progress\" Items",
      dashletGoLiveHideInProgress: "Hide \"In-Progress\" Items",
      dashletGoLiveColPageName: "Item Name",
      dashletGoLiveColEdit: "Edit",
      dashletGoLiveColURL: "URL",
      dashletGoLiveColPublishDate: "Publish Date & Time",
      dashletGoLiveColLastEditedBy: "Last Edited By",
      dashletGoLiveColLastEditedDate: "Last Edited",
      dashletGoLivePages: "Pages ({0})",
      dashletGoLiveComponents: "Components ({0})",
      dashletGoLiveAssets: "Assets ({0})",
      dashletGoLiveEdit: "Edit",

      dashletApprovedSchedTitle: "Approved Scheduled Items",
      dashletApprovedSchedCollapseAll: "Collapse All",
      dashletApprovedSchedExpandAll: "Expand All",
      dashletApprovedSchedShow: "Show",
      dashletApprovedSchedColGoLiveDate: "Go Live Date",
      dashletApprovedSchedColEdit: "Edit",
      dashletApprovedSchedColURL: "URL",
      dashletApprovedSchedColLastEdited: "Last Edited",

      dashletRecentDeployTitle: "Recently Published",
      dashletRecentDeployCollapseAll: "Collapse All",
      dashletRecentDeployExpandAll: "Expand All",
      dashletRecentDeployShow: "Show",
      dashletRecentDeployColMadeLiveDateDate: "Publish Date",
      dashletRecentDeployColEdit: "Edit",
      dashletRecentDeployColURL: "URL",
      dashletRecentDeployColEndpoint: "Server",
      dashletRecentDeployColDeployBy: "Published By",

      dashletMyRecentActivityTitle: "My Recent Activity",
      dashletMyRecentActivityHideLiveItems: "Hide Live Items",
      dashletMyRecentActivityShowLiveItems: "Show Live Items", 
      ddashletMyRecentActivityShow: "Show",
      dashletMyRecentActivityColPageName: "Item Name",
      dashletMyRecentActivityColEdit: "Edit",
      dashletMyRecentActivityColURL: "URL",
      dashletMyRecentActivityColPublishDate: "Publish Date",
      dashletMyRecentActivityColLastEditedBy: "Last Edited By",
      dashletMyRecentActivityColMyLastEdit: "My Last Edit",

      dashletIconGuideTitle: "Workflow Icon Guide",
      dashletIconGuideNavigationPage: "Navigation Page",
      dashletIconGuideFloatingPage: "Floating Page",
      dashletIconGuideComponent: "Komponenta",
      dashletIconGuideDocument: "Dokument",
      dashletIconGuideStateNew: "Never published",
      dashletIconGuideStateDisabled: "Disabled",
      dashletIconGuideStateDeleted: "Obrisano",
      dashletIconGuideStateInProgress: "Edited",
      dashletIconGuideStateInWorkflow: "In Workflow",
      dashletIconGuideStateScheduled: "Scheduled",
      dashletIconGuideStateSystemProcessing: "Processing",
      dashletIconGuideStateLocked: "Locked for edit",

});

CStudioAuthoring.Messages.registerBundle("contextnav", "en", { 
      siteContent: "Site Content",

      wcmContentEdit: "Edit",
      wcmContentView: "View",
      wcmContentSubmit: "Request Publish",
      wcmContentDelete: "Delete",
      wcmContentSubmitDelete: "Request Delete",
      wcmContentReject: "Reject",
      wcmContentSchedule: "Schedule",
      wcmContentApprove: "Approve & Publish",
      wcmContentDuplicate: "Duplicate",
      wcmContentHistory: "History",
      wcmContentPageDisabled: "Page is disabled: When deployed, a live visitor will see page not found (404) error.",
      
      InProgress: "Edited",
      Deleted: "Deleted",
      SubmittedforDelete: "Submitted for Delete",
      mixedStates: "Items (Mixed States)",
      Submitted: "Submitted for Publish",
      Live: "Live",
      Scheduled: "Scheduled",

      search: "Search",

      logout: "Log Out"

});
