# Crafter Studio Upgrade Configuration

pipelines:

  # Pipeline to upgrade system components (database, global repo, ...)
  system:
    - currentVersion: 3.0.0
      nextVersion: 3.0.1
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.0-to-3.0.1.sql
          updateIntegrity: false # Needs to be set to false in all version previous to 3.0.17

    - currentVersion: 3.0.1
      nextVersion: 3.0.2
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.1-to-3.0.2.sql
          updateIntegrity: false

    - currentVersion: 3.0.2
      nextVersion: 3.0.2.1
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.2-to-3.0.2.1.sql
          updateIntegrity: false

    - currentVersion: 3.0.2.1
      nextVersion: 3.0.10
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.2.1-to-3.0.10.sql
          updateIntegrity: false

    - currentVersion: 3.0.10
      nextVersion: 3.0.11
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.10-to-3.0.11.sql
          updateIntegrity: false

    - currentVersion: 3.0.11
      nextVersion: 3.0.11.1
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.11-to-3.0.11.1.sql
          updateIntegrity: false

    - currentVersion: 3.0.11.1
      nextVersion: 3.0.11.2
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.11.1-to-3.0.11.2.sql
          updateIntegrity: false

    - currentVersion: 3.0.11.2
      nextVersion: 3.0.11.3
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.11.2-to-3.0.11.3.sql
          updateIntegrity: false

    - currentVersion: 3.0.11.3
      nextVersion: 3.0.15
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.0.11.3-to-3.0.15.sql
        updateIntegrity: false

    - currentVersion: 3.0.15
      nextVersion: 3.0.15.1
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.0.15-to-3.0.15.1.sql
          updateIntegrity: false

    - currentVersion: 3.0.15.1
      nextVersion: 3.1.0
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.0.15.1-to-3.1.0.sql

    - currentVersion: 3.0.17
      nextVersion: 3.1.0
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.0.17-to-3.1.0.sql

    - currentVersion: 3.1.0
      nextVersion: 3.1.0.1
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0-to-3.1.0.1.sql
        - type: globalRepoUpgrader
          files:
            - configuration/global-menu-config.xml
            - configuration/global-permission-mappings-config.xml
            - configuration/global-role-mappings-config.xml

    - currentVersion: 3.1.0.1
      nextVersion: 3.1.0.2
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.1-to-3.1.0.2.sql

    - currentVersion: 3.1.0.2
      nextVersion: 3.1.0.3
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.2-to-3.1.0.3.sql

    - currentVersion: 3.1.0.3
      nextVersion: 3.1.0.4
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.3-to-3.1.0.4.sql
          updateIntegrity: false # Because the script only changes content

    - currentVersion: 3.1.0.4
      nextVersion: 3.1.0.5
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.1.0.4-to-3.1.0.5.sql
        updateIntegrity: true

    - currentVersion: 3.1.0.5
      nextVersion: 3.1.0.6
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.1.0.5-to-3.1.0.6.sql
        updateIntegrity: true

    - currentVersion: 3.1.0.6
      nextVersion: 3.1.0.7
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.1.0.6-to-3.1.0.7.sql
        updateIntegrity: true

    - currentVersion: 3.1.0.7
      nextVersion: 3.1.0.8
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.1.0.7-to-3.1.0.8.sql
        updateIntegrity: true
      - type: xsltFileUpgrader
        path: /configuration/global-menu-config.xml
        template: crafter/studio/upgrade/3.1.0.8/global-menu-config-2.xslt
      - type: xsltFileUpgrader
        path: /configuration/global-permission-mappings-config.xml
        template: crafter/studio/upgrade/3.1.0.8/global-permission-mappings-config-2.xslt

    - currentVersion: 3.1.0.8
      nextVersion: 3.1.0.9
      operations:
      - type: dbScriptUpgrader
        filename: upgrade-3.1.0.8-to-3.1.0.9.sql
        updateIntegrity: true

    - currentVersion: 3.1.0.9
      nextVersion: 3.1.0.10
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.9-to-3.1.0.10.sql
          updateIntegrity: true

    - currentVersion: 3.1.0.10
      nextVersion: 3.1.0.11
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.10-to-3.1.0.11.sql
          updateIntegrity: true

    - currentVersion: 3.1.0.11
      nextVersion: 3.1.0.12
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.11-to-3.1.0.12.sql
          updateIntegrity: true

    - currentVersion: 3.1.0.12
      nextVersion: 3.1.0.13
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.12-to-3.1.0.13.sql
          updateIntegrity: true

    - currentVersion: 3.1.0.13
      nextVersion: 3.1.0.14
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.13-to-3.1.0.14.sql
          updateIntegrity: true
        - type: xsltFileUpgrader
          path: /configuration/global-permission-mappings-config.xml
          template: crafter/studio/upgrade/3.1.0.14/global-permission-mappings-config-3.xslt

    - currentVersion: 3.1.0.14
      nextVersion: 3.1.0.15
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.14-to-3.1.0.15.sql
          updateIntegrity: true
        - type: globalRepoUpgrader
          files:
            - blueprints/empty/craftercms-plugin.yaml
            - blueprints/headless_blog/craftercms-plugin.yaml
            - blueprints/headless_store/craftercms-plugin.yaml
            - blueprints/website_editorial/craftercms-plugin.yaml

    - currentVersion: 3.1.0.15
      nextVersion: 3.1.0.16
      operations:
        - type: dbScriptUpgrader
          filename: upgrade-3.1.0.15-to-3.1.0.16.sql
          updateIntegrity: true

  # Pipeline to upgrade site repositories
  site:
    - currentVersion: 3.1.0
      nextVersion: 3.1.0.1
      operations:
        - type: addFileUpgrader
          path: /config/studio/administration/samples/sample-urlrewrite.xml
          file: crafter/studio/upgrade/3.1.0.1/sample-urlrewrite.xml
          commitDetails: Add sample file for url rewrite
        - type: versionFileUpgrader

    - currentVersion: 3.1.0.1
      nextVersion: 3.1.0.2
      operations:
        - type: addFileUpgrader
          path: /config/studio/administration/samples/sample-webdav.xml
          file: crafter/studio/upgrade/3.1.0.2/sample-webdav.xml
          commitDetails: Add sample file for webdav
        - type: versionFileUpgrader

    - currentVersion: 3.1.0.2
      nextVersion: 3.1.0.3
      operations:
        - type: addSiteUuidUpgrader
        - type: versionFileUpgrader

    - currentVersion: 3.1.0.3
      nextVersion: 3.1.0.4
      operations:
        - type: boxControlUpgrader
          includedPaths: /?site/.*\.xml
          formDefinitionXpath: /form/sections/section/fields/field/type[text()='box-file-upload']
          fieldNameXpath: /form/sections/section/fields/field/type[text()='box-file-upload']/../id
          profileIdXpath: /form/sections/section/fields/field/id[text()='${id}']/../properties/property/name[text()='profile_id']/../value
          itemXpath: //${id}/item
          itemIdXpath: id
          itemNameXpath: name
          urlElementName: url
          urlTemplate: /remote-assets/box/${profile}/${id}.${extension}
          commitDetails: Add new <url> tag to fields that use the Box File Upload control
        - type: versionFileUpgrader

    - currentVersion: 3.1.0.4
      nextVersion: 3.1.0.5
      operations:
        - type: addFileUpgrader
          path: /config/studio/form-control-config/rte/rte-setup-tinymce4.xml
          file: crafter/studio/upgrade/3.1.0.5/rte-setup-tinymce5.xml
        - type: addFileUpgrader
          path: /config/studio/administration/samples/sample-form-control-rte-setupt-tinymce5.xml
          file: crafter/studio/upgrade/3.1.0.5/sample-form-control-rte-setupt-tinymce5.xml
        - type: versionFileUpgrader

    # For older sites just add the version file (those will require a manual upgrade)
    - currentVersion: 3.0.x
      nextVersion: 3.0.x
      operations:
        - type: versionFileUpgrader

  # Pipeline to upgrade blueprints
  blueprint:
    - currentVersion: 3.0.0
      nextVersion: 3.1.0
      operations:
        # This just overrides the blueprints in the repo, in the future this should be replaced with proper operations
        - type: blueprintsUpgrader

# Managed Configuration Files
configurations:

  role-mappings-config:
    path: &role-mappings-config '/config/studio/role-mappings-config.xml'
    pipeline:
      # Initial version, assumed if the file doesn't contain a version tag
      - currentVersion: 1
        nextVersion: 2
        operations:
          - type: xsltFileUpgrader
            path: *role-mappings-config
            template: crafter/studio/upgrade/3.1.0/role-mappings-config-2.xslt
            commitDetails: Update role mappings configuration
          - type: xsltFileUpgrader
            path: *role-mappings-config
            template: crafter/studio/upgrade/update-version.xslt

  config-list:
    path: &config-list '/config/studio/administration/config-list.xml'
    pipeline:
      # Initial version, assumed if the file doesn't contain a version tag
      - currentVersion: 1
        nextVersion: 2
        operations:
          - type: xsltFileUpgrader
            path: *config-list
            template: crafter/studio/upgrade/3.1.0.1/config-list-2.xslt
            commitDetails: Add url rewrite to configuration list
          - type: xsltFileUpgrader
            path: *config-list
            template: crafter/studio/upgrade/update-version.xslt
      - currentVersion: 2
        nextVersion: 3
        operations:
          - type: xsltFileUpgrader
            path: *config-list
            template: crafter/studio/upgrade/3.1.0.2/config-list-3.xslt
            commitDetails: Add webdav to configuration list
          - type: xsltFileUpgrader
            path: *config-list
            template: crafter/studio/upgrade/update-version.xslt

  site-config-tools:
    path: &site-config-tools '/config/studio/administration/site-config-tools.xml'
    pipeline:
      - currentVersion: 1
        nextVersion: 2
        operations:
          - type: xsltFileUpgrader
            path: *site-config-tools
            template: crafter/studio/upgrade/3.1.0.2/site-config-tools-2.xslt
            commitDetails: Add webdav datasources to site configuration
          - type: xsltFileUpgrader
            path: *site-config-tools
            template: crafter/studio/upgrade/update-version.xslt
      - currentVersion: 2
        nextVersion: 3
        operations:
          - type: xsltFileUpgrader
            path: *site-config-tools
            template: crafter/studio/upgrade/3.1.0.5/site-config-tools-3.xslt
          - type: xsltFileUpgrader
            path: *site-config-tools
            template: crafter/studio/upgrade/update-version.xslt