# Crafter Studio Upgrade Configuration

pipelines:

  # Pipeline to upgrade system components (database, global repo, ...)
  system:
    # Direct upgrades from 3.1.8 or previous to 3.2.x are not supported, only from 3.1.9+
    requires: '>=3.1.9'
    versions:
      - currentVersion: 3.1.9.3
        nextVersion: 3.2.0.1
        operations:
          - type: globalRepoUpgrader
            files:
              - src: repo-bootstrap/global/configuration/samples/sample-translation-config.xml
                dest: configuration/samples/sample-translation-config.xml
            commitDetails: Add sample file for translation-config.xml
      - currentVersion: 3.2.0.1
        nextVersion: 3.2.0.2
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.1-to-3.2.0.2.sql
      - currentVersion: 3.2.0.2
        nextVersion: 3.2.0.3
        operations:
          - type: globalRepoUpgrader
            files:
              - src: repo-bootstrap/global/configuration/samples/sample-permission-mappings-config.xml
                dest: configuration/samples/sample-permission_mappings-config.xml
            commitDetails: Add sample file for translation-config.xml
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.2-to-3.2.0.3.sql
      - currentVersion: 3.2.0.3
        nextVersion: 3.2.0.4
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.3-to-3.2.0.4.sql
      - currentVersion: 3.2.0.4
        nextVersion: 3.2.0.5
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.4-to-3.2.0.5.sql
      - currentVersion: 3.2.0.5
        nextVersion: 3.2.0.6
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.5-to-3.2.0.6.sql
      - currentVersion: 3.2.0.6
        nextVersion: 3.2.0.7
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.6-to-3.2.0.7.sql
      - currentVersion: 3.2.0.7
        nextVersion: 3.2.0.8
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.7-to-3.2.0.8.sql
      - currentVersion: 3.2.0.8
        nextVersion: 3.2.0.9
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.8-to-3.2.0.9.sql
      - currentVersion: 3.2.0.9
        nextVersion: 3.2.0.10
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.9-to-3.2.0.10.sql
      - currentVersion: 3.2.0.10
        nextVersion: 3.2.0.11
        operations:
          - type: populateItemTableUpgrader
            filename: upgrade-3.2.0.10-to-3.2.0.11.sql
            spName: populateItemTable
            clearExistingData: true
      - currentVersion: 3.2.0.11
        nextVersion: 3.2.0.12
        operations:
          - type: xsltFileUpgrader
            path: /configuration/global-permission-mappings-config.xml
            template: crafter/studio/upgrade/3.2.x/3.2.0.12/system/global-permission-mappings-config.xslt
            commitDetails: Add new permission 'edit_site'
      - currentVersion: 3.2.0.12
        nextVersion: 3.2.0.13
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.12-to-3.2.0.13.sql
      - currentVersion: 3.2.0.13
        nextVersion: 3.2.0.14
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.13-to-3.2.0.14.sql
      - currentVersion: 3.2.0.14
        nextVersion: 3.2.0.15
        operations:
          - type: globalRepoUpgrader
            files:
              - src: repo-bootstrap/global/configuration/samples/sample-urlrewrite.xml
                dest: configuration/samples/sample-urlrewrite.xml
            commitDetails: Update sample file for urlrewrite.xml
      - currentVersion: 3.2.0.15
        nextVersion: 3.2.0.16
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.15-to-3.2.0.16.sql
      - currentVersion: 3.2.0.16
        nextVersion: 3.2.0.17
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.16-to-3.2.0.17.sql
      - currentVersion: 3.2.0.17
        nextVersion: 3.2.0.18
        operations:
          - type: globalRepoUpgrader
            files:
              - src: repo-bootstrap/global/configuration/samples/sample-webdav.xml
                dest: configuration/samples/sample-webdav.xml
            commitDetails: Update sample file for webdav.xml
          - type: dbVersionUpgrader
      - currentVersion: 3.2.0.18
        nextVersion: 3.2.0.19
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.18-to-3.2.0.19.sql
      - currentVersion: 3.2.0.19
        nextVersion: 3.2.0.20
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.19-to-3.2.0.20.sql
      - currentVersion: 3.2.0.20
        nextVersion: 3.2.0.21
        operations:
          - type: dbScriptUpgrader
            filename: upgrade-3.2.0.20-to-3.2.0.21.sql

  # Pipeline to upgrade site repositories
  site:
    # Direct upgrades from 3.1.8 or previous to 3.2.x are not supported, only from 3.1.9+
    requires: '>=3.1.9'
    versions:
      - currentVersion: 3.1.9
        nextVersion: 3.2.0
        operations:
          - type: addFileUpgrader
            path: /config/studio/translation-config.xml
            file: crafter/studio/upgrade/3.2.x/3.2.0/site/translation-config.xml
            commitDetails: Add translation config

  # Pipeline to upgrade blueprints
  blueprint:
    - currentVersion: 3.0.0
      nextVersion: 3.1.0
      operations:
        # This just overrides the blueprints in the repo, in the future this should be replaced with proper operations
        - type: renameUpgrader
          oldPath: blueprints/website_editorial
          newPath: blueprints/1000_website_editorial
          commitDetails: Rename Editorial blueprint
          overwrite: true
        - type: renameUpgrader
          oldPath: blueprints/headless_store
          newPath: blueprints/2000_headless_store
          commitDetails: Rename Headless Store blueprint
          overwrite: true
        - type: renameUpgrader
          oldPath: blueprints/video-center
          newPath: blueprints/3000_video-center
          commitDetails: Rename Video Center blueprint
          overwrite: true
        - type: renameUpgrader
          oldPath: blueprints/empty
          newPath: blueprints/4000_empty
          commitDetails: Rename Empty blueprint
          overwrite: true
        - type: renameUpgrader
          oldPath: blueprints/headless_blog
          newPath: blueprints/5000_headless_blog
          commitDetails: Rename Headless Blog blueprint
          overwrite: true
        - type: blueprintsUpgrader

# Managed Configuration Files
configurations:

  studio-site-config:
    module: studio
    path: site-config.xml
    pipeline:
      requires: '>=7'
      # Add new versions as needed, starting on 7
      # versions:


  permission-mappings-config:
    module: studio
    path: permission-mappings-config.xml
    pipeline:
      requires: '>=12'
      versions:
        - currentVersion: 12
          nextVersion: 13
          operations:
            - type: xsltFileUpgrader
              template: crafter/studio/upgrade/3.2.x/config/permission-mappings-config/permission-mappings-config-v13.xslt
              commitDetails: Added get_children permission
        - currentVersion: 13
          nextVersion: 14
          operations:
            - type: xsltFileUpgrader
              template: crafter/studio/upgrade/3.2.x/config/permission-mappings-config/permission-mappings-config-v14.xslt
              commitDetails: Add new permission 'edit_site'

  role-mappings-config:
    module: studio
    path: role-mappings-config.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:


  config-list:
    module: studio
    path: administration/config-list.xml
    pipeline:
      requires: '>=10'
      versions:
        - currentVersion: 10
          nextVersion: 11
          operations:
            - type: xsltFileUpgrader
              template: crafter/studio/upgrade/3.2.x/config/config-list/config-list-v11.xslt
              commitDetails: Add translation config

  site-config-tools:
    module: studio
    path: administration/site-config-tools.xml
    pipeline:
      requires: '>=11'
      # Add new versions as needed, starting on 11
      # versions:


  contextual-nav:
    module: studio
    path: context-nav/contextual-nav.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  aws:
    module: studio
    path: aws/aws.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  box:
    module: studio
    path: box/box.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  webdav:
    module: studio
    path: webdav/webdav.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  notification-config:
    module: studio
    path: workflow/notification-config.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  code-editor-config:
    module: studio
    path: code-editor-config.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  engine-site-config:
    module: engine
    path: site-config.xml
    pipeline:
      requires: '>=2'
      # Add new versions as needed, starting on 2
      # versions:

  proxy-config:
    module: engine
    path: proxy-config.xml
    pipeline:
      requires: '>=3'
      # Add new versions as needed, starting on 3
      # versions:

  urlrewrite:
    module: engine
    path: urlrewrite.xml
    pipeline:
      - currentVersion: 1
        nextVersion: 2
        operations:
          - type: xsltFileUpgrader
            template: crafter/studio/upgrade/copy.xslt
            commitDetails: Remove doctype declaration
