CStudioAuthoring.Messages.registerBundle("siteDashboard", "es", {
    dashboardTitle: "Panel de Control de {0}",

    dashboardCollapseAll: "Desplegar todo",
    dashboardExpandAll: "Expandir todo",
    dashboardEdit: "Editar",

    approvedScheduledCollapseAll: "Desplegar todo",

    dashletFilterPages: "Páginas",
    dashletFilterComponents: "Componentes",
    dashletFilterDocuments: "Documentos",
    dashletFilterAssets: "Recursos",
    dashletFilterAll: "Todo",

    dashletGoLiveQueueTitle: "Articulos Esperando por Aprobación",
    dashletGoLiveCollapseAll: "Desplegar todo",
    dashletGoLiveExpandAll: "Expandir todo",
    dashletGoLiveShowInProgress: "Mostrar Artículos \"En-Progreso\" ",
    dashletGoLiveHideInProgress: "Esconder Artículos \"En-Progreso \" ",
    dashletGoLiveColPageName: "Nombre del Artículo",
    dashletGoLiveColEdit: "Editar",
    dashletGoLiveColURL: "URL",
    dashletGoLiveColPublishDate: "Fecha y Hora de Publicación",
    dashletGoLiveColLastEditedBy: "Ultima Edición por",
    dashletGoLiveColLastEditedDate: "Última Edición",
    dashletGoLivePages: "Páginas ({0})",
    dashletGoLiveComponents: "Componentes ({0})",
    dashletGoLiveAssets: "Recursos ({0})",
    dashletGoLiveEdit: "Editar",

    dashletApprovedSchedTitle: "Artículos Publicados",
    dashletApprovedSchedCollapseAll: "Desplegar todo",
    dashletApprovedSchedExpandAll: "Expandir todo",
    dashletApprovedSchedShow: "Mostrar",
    dashletApprovedSchedColGoLiveDate: "Fecha para ir en Vivo",
    dashletApprovedSchedColEdit: "Editar",
    dashletApprovedSchedColURL: "URL",
    dashletApprovedSchedColLastEdited: "Última Edición",
    dashletApprovedSchedFilterPages: "Páginas",
    dashletApprovedSchedFilterComponents: "Componentes",
    dashletApprovedSchedFilterDocuments: "Documentos",
    dashletApprovedSchedFilterAll: "Todo",

    showNumItems: "Mostrar",

    dashletRecentDeployTitle: "Recientemente Publicados",
    dashletRecentDeployCollapseAll: "Desplegar todo",
    dashletRecentDeployExpandAll: "Expandir todo",
    dashletRecentDeployShow: "Mostrar",
    dashletRecentDeployColMadeLiveDateDate: "Fecha de Publicación",
    dashletRecentDeployColEdit: "Editar",
    dashletRecentDeployColURL: "URL",
    dashletRecentDeployColEndpoint: "Servidor",
    dashletRecentDeployColDeployBy: "Publicado por",
    dashletRecentDeployColLastEdited: "Última Edición",

    dashletMyRecentActivityTitle: "Mi actividad reciente",
    dashletMyRecentActivityHideLiveItems: "Enconder Artículos en Vivo",
    dashletMyRecentActivityShowLiveItems: "Mostrar Artículos en Vivo",
    ddashletMyRecentActivityShow: "Mostrar",
    dashletMyRecentActivityColPageName: "Nombre del Artículo",
    dashletMyRecentActivityColEdit: "Editar",
    dashletMyRecentActivityColURL: "URL",
    dashletMyRecentActivityColPublishDate: "Fecha de Publicación",
    dashletMyRecentActivityColLastEditedBy: "Ultima Edición por",
    dashletMyRecentActivityColMyLastEdit: "Mi Ultima Edición",

    dashletIconGuideTitle: "Icono de guía de flujo de trabajo ",
    dashletIconGuideNavigationPage: "Pagina de Navegación",
    dashletIconGuideFloatingPage: "Página flotante",
    dashletIconGuideComponent: "Componente",
    dashletIconGuideDocument: "Documento",
    dashletIconGuideStateNew: "Nunca Piblicado",
    dashletIconGuideStateDisabled: "Disabled",
    dashletIconGuideStateDeleted: "Eliminado",
    dashletIconGuideStateInProgress: "Editado",
    dashletIconGuideStateInWorkflow: "En Flujo de Trabajo",
    dashletIconGuideStateScheduled: "Programado",
    dashletIconGuideStateSystemProcessing: "Procesando",
    dashletIconGuideStateLocked: "Bloqueado para editar"

});

CStudioAuthoring.Messages.registerBundle("contextnav", "es", {
    siteContent: "Contenido del Sitio",

    wcmContentEdit: "Editar",
    wcmContentView: "Ver",
    wcmContentSubmit: "Solicitud de Publicación",
    wcmContentDelete: "Eliminar",
    wcmContentSubmitDelete: "Solicitud de Eliminación",
    wcmContentReject: "Rechazar",
    wcmContentSchedule: "Programar",
    wcmContentApprove: "Aprobar y Publicar",
    wcmContentDuplicate: "Duplicar",
    wcmContentHistory: "Historial",
    wcmContentPageDisabled: "Page is disabled: When deployed, a live visitor will see page not found (404) error.",

    InProgress: "Editado",
    Deleted: "Eliminado",
    SubmittedforDelete: "Presentado para Eliminar",
    mixedStates: "Artículos (Estados Mixtos)",
    Submitted: "Presentado para Aprobar",
    Live: "En Vivo",
    Scheduled: "Programado",

    search: "Busqueda",

    logout: "Cerrar Sesión",

    variableLabel: "Ejemplos de Código de Plantilla"

});

CStudioAuthoring.Messages.registerBundle("previewTools", "es", {
    previewToolsTitle: "Herramientas de Vista Previa",
    inContextEditing: "Edición En-Contexto",
    pageComponents: "Componentes de Página",
    responsivePreview: "Vista Previa Responsive",
    desktop: "Escritorio",
    browser: "Navegador",
    iphone: "iPhone5 / iPhone5S",
    iPad: "iPad",
    targeting: "Orientación",
    analytics: "Análisis",
    translation: "Traducción",
    inContextEditOn: "Encender Edición En-Contexto",
    inContextEditOff: "Apagar Edición En-Contexto",
    publishingChannel: "Canal para Publicar",
    web: "Web",
    smartPhone: "Teléfono Inteligente",
    tablet: "Tableta",
    multiVariantTesting: "Pruebas Multi-Variante",
    YellowVsBlue: "Máscaras Amarillas vs Azul en Inicio",
    yellow: "Amarillo",
    blue: "Azul",
    FacetedVsKeyword: "Buscar: Facetas vs Palabra Clave",
    faceted: "Facetas",
    facetedKeyword: "Facetas + Palabra Clave",
    keywordOnly: "Solo Palabra Clave",
    HomeRedVsBlue: "Botones de Inicio Rojo vs Azul",
    red: "Rojo",
    catalogPageSorting: "Ordernar Página del Catálogo",
    arrivalDate: "Fecha de Llegada",
    priceHightoLow: "Precio de mayor a menor",
    priceLowtoHigh: "Precio de menor a mayor",
    editTemplate: "Editar Plantilla",
    jumpToRegion: "Saltar a la Región",
    dimensionsPx: "Dimensiones (px)",
    presets: "Preajustes",
    custom: "Personalizado",
    addComponent: "Añadir componentes",
    done: "Terminado",
    general: "General",
    components: "Componentes",
    persona: "Persona",
    properties: "Propiedades",
    assume: "Asumir",
    update: "Actualizar",
    active: "Activo",
    reportsOff: "Reportes Fuera",
    reportsError: "Incapaz de rendir informe debido a error",
    addComponent :"Añadir componentes",
    done: "Listo",
    components: "Componentes",
    general: "General",
    text: "Texto"

});

CStudioAuthoring.Messages.registerBundle("siteDropdown", "es", {
    pages: "Páginas",
    Pages: "Páginas",
    page: "Página",
    components: "Componentes",
    Components: "Componentes",
    component: "Componente",
    staticassets: "Activos Estáticos",
    templates: "Plantillas",
    scripts: "Scripts",
    analyticsDashboard: "Panel de Control de Análisis",
    adminConsole: "Consola de Administración",
    previewSync: "Vista previa de Sincronización",
    allSites: "Todos los Sitios",
    newContent: "Nuevo Contenido",
    newFolder: "Nueva Carpeta",
    upload: "Subir",
    edit: "Editar",
    view: "Ver",
    changeTemplate: "Cambiar la Plantilla",
    delete: "Eliminar",
    cut: "Cortar",
    copy: "Copiar",
    paste: "Pegar",
    history: "Historial",
    unlock: "Desbloquear",
    noActionsAvailable: "No Hay Acciones Disponibles",
    createFolder: "Crear Carpeta",
    createTemplate: "Crear Plantilla",
    createController: "Crear Controlador",
    bulkUploadAssets: "Subir Activos Granel",
    lastEdited: "Última Edición",
    editedBy: "Editado Por",
    lockedBy: "Bloqueado Por",
    status: "Estado",
    scheduled: "Programado",
    loading: "Cargando...",

    /*tooltip-Status*/
    statusDeleted: "Eliminado",
    statusScheduledForDelete: "Programado para Eliminar",
    statusSubmittedForDelete: "Presentado para Eliminar",
    statusAndDisabled: "y Deshabilitado",
    statusProcessing: "Procesando",
    statusInProgress: "En Progreso",
    statusLive: "En Vivo",
    statusAnd: "y",
    statusSubmitted: "Enviado",
    statusScheduled: "Programado",
    statusDisabled: "Deshabilitado"

});

CStudioAuthoring.Messages.registerBundle("forms", "es", {
    expandAll: "Expandir Todo",
    collapseAll: "Collapsar Todo",
    pageName: "Item Name",
    location: "Ubicación",
    sectionValidation: "{0} de {1} campos requeridos son invalidos",
    saveAndClose: "Guardar y Cerrar",
    saveAndPreview: "Guardar y Mostrar",
    save: "Guardar",
    cancel: "Cancelar",
    close: "Cerrar",
    repeatAddAnother: "Agregar Otro",
    repeatMoveUp: "Mover Arriba",
    repeatMoveDown: "Mover Abajo",
    repeatDelete: "Eliminar",
    errMissingRequirements: "You cannot save until all form requirements are satisfied",
    errSaveFailed: "Unable to save form content. Please try again or contact or your system administrator.",
    errOnRepeat: "Error on repeater operation: {0}",
    errFailedToLoadContent: "Error loading content: {0}",
    errExpectedIndexXml: "Not expecting file-name other than index.xml",
    ok: "Aceptar",
    yes: "Si",
    no: "No",
    submit:"Enviar",
    loading:"Cargando&hellip;",
    viewSample: "Ver Ejemplo",
    hideSample: "Esconder Ejemplo",

    copy: "Copiar",
    copyDescription: "Por favor seleccione las subpaginas que le gustaria copar.<br/> Al pegar, se conservarán las sub-páginas seleccionadas y su jerarquía posicional.",
    page: "Página",
    loadingContents: "Loading contents ...",
    cut: "Cut",
    cutDescription: "Por favor seleccione las subpaginas que le gustaria cortar.<br/> Al pegar, se conservarán las sub-páginas seleccionadas y su jerarquía posicional.",

    create: "Crear",
    newFolderTitle: "Crear una carpeta nueva",
    newFolderBody: "Porfavor ingrese el nombre de la carpeta",
    newFolderLabel: "Nombre de la carpeta:",
    newFolderUpdating: "Creando la carpeta...",

    chooseContentType: "Elige un tipo de contenido",
    chooseContentTypeBody: "Las siguientes plantillas de inicio están disponibles para su uso dentro de esta sección.",
    chooseContentTypeLabel: "Nombre de la Plantilla:",
    chooseContentTypePreview: "Vista Previa:",

    cancelDialogHeader:"Crafter Studio",
    cancelDialogBody:"Desea cerrar este formulario sin guardar los cambios?",

    changeTemplateDialogTitle:"Advertencia: Cambiando el Tipo de Contenido",
    changeTemplateDialogSubTitle:"Crafter Studio",
    changeTemplateDialogBody:"La siguiente operación puede provocar la pérdida de datos. ¿Quieres continuar?",

    historyDialogTitle: "Historial de las Versiones",
    historyDialogSubTitle: "Historial mostrado para:",
    historyDialogTableRowVersion: "Versión",
    historyDialogTableRowTime: "Tiempo de Edición",
    historyDialogTableRowEditBy: "Editado por",
    historyDialogTableRowComment: "Comentario",
    historyDialogRevert: "Revertir",
    historyDialogLoadingWait: "Cargando, por favor esperar&hellip;",
    historyDialogNoVersionsFound: "No hay versiones encontradas.",
    historyDialogUnable:"No se puede cargar el historial de versiones.",
    historyDialogTryAgain:"Inténtalo de nuevo",

    deleteDialogTitle:"Eliminar",
    deleteDialogSubTitle:"Los siguientes elementos seleccionados serán eliminados:",
    deleteDialogSetLink:'Establecer todo para "Ahora"',
    deleteDialogPage:"Página",
    deleteDialogDelete:"Eliminar",
    deleteDialogNow:"Ahora",
    deleteDialogFeedBack:"Las dependencias deben comprobarse antes de enviarlas",
    deleteDialogNoItemsSelected:"No hay artículos seleccionados",

    deleteSubmitDialogTitle:"Enviar para su eliminación",
    deleteSubmitDialogTime:"¿Cuándo desea eliminar los artículos marcados?",
    deleteSubmitEmailMe:"Enviarme un correo cuando los artículos son eliminados.",
    deleteSubmitDialogAsSoon:"Lo antes posible.",

    approveDialogTitle: "Aprobar para Publicar",
    approveDialogSubTitle: "Los siguientes elementos seleccionados estarán en vivo.",
    approveDialogPage: "Página",
    approveDialogOriginalSchedule: "Horario original",
    approveDialogSubmissionComment: "Comentario de envio",
    approveDialogSelectedScheduling: "Seleccionado artículo Programado",
    approveDialogItemsLiveNow: "Los artículos deben ir en vivo ahora.",
    approveDialogItemsLiveDate: "Los artículos irán en vivo en una fecha y hora específica",
    approveDialogPublishContent: "Publicar Contenido",
    approveDialogPublishingOptions: "Opciones de Publicación",
    approveDialogBroadcastUpdate: "Actualización de contenido",

    requestApproveDialogTitle: "Solicitud de Publicación",
    requestApproveDialogSubTitle: "Cuando desea que los artiículos vayan en vivo?",
    requestApproveDialogEmailMe: "Enviarme un correo cuando los artículos esten en vivo.",

    newContTypeDialogTitle: "Crear Tipo de Contenido",
    newContTypeDialogDisplayLabel: "Etiqueta a Mostrar",
    newContTypeDialogContentTypeName: "Nombre",
    newContTypeDialogType: "Tipo",
    newContTypeDialogPage: "Página",
    component: "Componente",
    newContTypeDialogLabelMsg: "Proporcione una etiqueta de visualización de este Tipo de Contenido",
    newContTypeDialogContentTypeNamelMsg: "Proporcione un nombre de sistema para este Tipo de Contenido",
    newContTypeDialogTypeMsg: "Seleccione el tipo de este Tipo de Contenido",

    adminHelpDialogTitle: "Contenido del Campo",

    adminKeyValDialogTitle: "Valores",
    adminKeyValDialogKey: "Clave",
    adminKeyValDialogValue: "Valor",
    addAnother: "Agregar Otro",

    supportedChannelsDialogLabel: "Etiqueta",
    supportedChannelsDialogName: "Nombre",
    supportedChannelsDialogSize :"Tamaño",

    setStatedDialogTitle: "Seleccione Estados",
    setStatedDialogSetStates: "Establezca Estados",
    setStatedDialogSystemProcessing: "Procesamiento de Sistema",

    currentPage: "Página Actual"

});

CStudioAuthoring.Messages.registerBundle("search", "es", {
    defaultTitle: "Busqueda WCM",
    searchButtonLabel: "Busqueda",
    keywordsLabel: "Palabras Claves (opcional)",
    searchResults: "Resultados de la búsqueda",
    showing: "(Mostrando {0}-{1} de {2})",
    hideDescriptions: "Ocultar Descripciones",
    showDescriptions: "Mostrar Descripciones",
    show: "Mostrar",
    sort: "Ordenar",
    sortRelevance: "Por Relevancia",
    sortAlphabetical: "Alfabéticamente",
    sortCreateDate: "Por Fecha de Creación",
    pagePrevious: "Anterior",
    pageNext: "Siguiente",
    resultsEdited: "Editado",
    resultsBy: "Por",
    resultsUnknownType: "Tipo Desconocido",
    resultsTemplate: "Plantilla",
    errSearchFailed: "Busqueda Fallida. Trate de ajustar sus filtros. Causa: Si el problema persiste contacte al administrador y consultele el siguiente error: {0}",
    errNoResults: "Su búsqueda no produjo resultados."
});

CStudioAuthoring.Messages.registerBundle("contentTypes", "es", {
    contentTypes: "Tipos de Contenido",
    configuration: "Configuración",
    workflowJobs: "Flujo de Trabajo de Empleos",
    workflowStates: "Flujo de Trabajo de Estados",
    loggingLevels: "Niveles de Registro",
    logConsole: "Consola de Log",
    label: "Tipos de contenido",
    openExistingType: "Abrir un Tipo Existente",
    createNewType: "Crear un Nuevo Tipo",
    save: "Guardar",
    saved: "Guardado",
    saveFailed: "No Se Pudo Guardar",
    formSection: "Sección del Formulario",
    repeatingGroup: "Repetir Grupo",
    minOccurs: "Mínimo de Ocurrencias",
    maxOccurs: "Máximo de Ocurrencias",
    formBasics: "Conceptos básicos del formulario",
    formTitle: "Título",
    description: "Descripción",
    objectType: "Tipo de Objeto",
    contentType: "Tipo de Contenido",
    datasourceBasics: "Conceptos básicos de origen de datos",
    title: "Título",
    name: "Nombre",
    properties: "Propiedades",
    sectionBasics: "Sección de Fundamentos",
    variableName: "Nombre / Nombre de la variable",
    iceGroup: "Grupo ICE",
    fieldBasics: "Fundamentos de Campo",
    defaultValue: "Valor por defecto",
    help: "Ayuda",
    constraints: "Restricciones",
    propertiesExplorer: "Propiedades de Explorador",
    controls: "Controles",
    datasources: "Fuentes de Datos",
    defaultOpen: "Abrir por Defecto",
    showInNav: "Mostrar en Navegación",
    descriptorMapper: "Descriptor del Mapeo",

    /*Controls*/
    textArea: "Área de Texto",
    richTextEditor: "Editor de Texto Enriquecido",
    input: "Campo de Entrada",
    dropdown: "Menú Desplegable",
    dateTime: "Fecha Y Hora",
    checkBox: "Casilla de Verificación",
    groupedCheckboxes: "Grupo de Casillas de Verificación",
    itemSelector: "Selector de Elementos",
    image: "Imagen",
    video: "Video",
    label: "Etiqueta",
    pageOrder: "Orden de Páginas",
    fileName: "Nombre del Archivo",
    autoFilename: "Generar Nombre",
    forceHTTPS: "Forzar HTTPS",
    disabled: "Discapacitados",
    flash: "Flash",
    internalName: "Nombre Interno",

    /*Datasources */
    childContent: "Contenido Hijos",
    imageUploadedDesktop: "Imagen Subida desde el Escritorio",
    DAMImage: "Imagen DAM (Flickr)",
    fileUploadedDesktop: "Archivo Subido desde el Escritorio",
    flashUploadedDesktop: "Flash Subido desde el Escritorio",
    videoUploadedDesktop: "Video Subido desde el Escritorio",
    staticKeyValuePairs: "Pares Estáticos de Valores Clave",
    configuredListOfPairs: "Configurado Lista de Pares",
    fileBrowse: "Navegador de Archivos",
    hubspotForms: "Formularios Hubspot",
    imageFromRepository: "Imagen del repositorio",
    salesforceCampaigns: "Campañas de Salesforce",
    treeContent: "Contenido del Árbol",

    /*Properties*/
    Size: "Tamaño",
    maxLength: "Tamaño Máximo",
    width: "Ancho",
    height: "Altura",
    allowResize: "Permitir Cambio de Tamaño",
    forceRootBlockP: "Forzar Etiqueta p en Bloque ",
    forcePNewLines: "Forzar Etiqueta p en Línea",
    forceBRNewLines: "Forzar Etiqueta p en Nueva Línea",
    requireImageAlt: "Propiedad Alt de Imágen Requerida",
    supportedChannels: "Canales soportados",
    RTEConfiguration: "Configuración RTE",
    imageManager: "Administrador de Imágenes",
    showDate: "Mostrar Fecha",
    showTime: "Mostrar Hora",
    setNowLink: "Establecer Link de Ahora",
    populated: "Poblado",
    allowPastDate: "Permitir Fecha Pasada",
    readonly: "Solo Lectura",
    readonlyOnEdit: "Editar en Solo Lectura",
    datasource: "Fuentes de Dato",
    showSelectAll: 'Mostrar "Seleccionar Todo"',
    allowEmptyValue: "Permitir Valor Vacío",
    thumbnailWidth: "Ancho de Imágen Miniatura",
    thumbnailHeight: "Altura de Imágen Miniatura",
    displaySize: "Tamaño a Mostrar",
    text: "Texto",
    minSize: "Tamaño Mínimo",
    maxSize: "Tamaño Máximo",
    itemManager: "Administración de Elementos",
    disableFlatteningSearch: "Desactivar Acoplamiento de Búsqueda",
    singleValueFilename: "Utilizar solo el nombre de archivo de valor (compat hacia atrás)",
    columns: "Columnas",
    rows: "Filas",
    dataType: "Tipo de Dato",
    listName: "Nombre de la Lista",
    repositoryPath: "Ubicación del Repositorio",
    string: "Cadena de Caracteres",
    integer: "Numérico",
    float: "Decimal",
    date: "Fecha",
    HTML: "HTML",
    options: "Opciones",
    showKeys: "Mostrar Claves (Artículo Sel. Solamente)",
    taxonomyName: "Nombre de Taxonomía",
    defaultType: "Tipo por Defecto",
    displayTemplate: "Plantilla de Pantalla",
    mergeStrategy: "Combinar Estrategia",

    /*Restrictions*/
    required: "Requerido",
    minimumSelection: "Selección Mínima",
    matchPattern: "Patrón de Compatibilidad",
    allowDuplicate: "Permitir Duplicados",

    /*Values*/
    noDatasources: "No hay fuentes de datos disponibles para este control",
    editMessage: "Editar el mensaje",
    setMessage: "Agregar el mensaje",

    /*States Workflow*/
    setStatedTabID: "ID",
    setStatedTabState: "Estado",
    setStatedTabSystemProcessing: "Procesamiento de Sistema",
    setStatedTabSelectAll: "Seleccionar Todo",
    false: "Falso",
    true: "Verdadero",

    /*Jobs Workflow*/
    jobWorkflowTabAct: "Ley",
    jobWorkflowTabJobID: "Id del Empleo",
    jobWorkflowTabProcessName: "Nombre del Proceso",
    jobWorkflowTabCreatedDate: "Fecha<br/>de Creación",
    jobWorkflowTabModifiedDate: "Fecha<br/>de Modificación",
    jobWorkflowTabSiteId: "Id del Sitio",
    jobWorkflowTabItemsInJob: "Los ítems <br/> de Trabajo",
    jobWorkflowTabProperties: "Propiedades",
    jobWorkflowTabStatus: "Estado",

    /*Loggin Levels*/
    logginLevelsTabLogger: "Logger",
    logginLevelsTabCurrentLevel: "Nivel Actual",
    logginLevelsTabChangeLevel: "Cambiar Nivel a",
    debug: "depurar",
    warn: "advertir",
    info: "info",
    error: "error",

    /*Configuration*/
    confTabSelectConf: "Seleccione la Configuracioón",
    confTabConfigurations: "Configuraciones",
    confTabConfDesc: "Define esta lista de configuraciones",
    confTabAdminTools: "Herramientas de Administración",
    confTabAdminToolsDesc: "Define la lista de herramientas de administración disponibles",
    confTabAnalyticsDashboardConf: "Configuración de Panel de Control de Análisis",
    confTabAnalyticsDashboardConfDesc: "Define los tipos de informes que se muestran en el Panel de Control de Análisis",
    confTabAnalyticsPreviewConf: "Vista previa de Configuración de Análisis",
    confTabAnalyticsReportConf: "Informe de Configuración de Análisis",
    confTabContextualNavigationConf: "Configuración de Navegación Contextual",
    confTabContextualNavigationConfDesc: "Define los módulos de la barra de navegación contextual del sitio",
    confTabSiteDropdownConf: "Configuración del Menu Desplegable del sitio",
    confTabSiteDropdownConfDesc: "Define los módulos de la barra desplegable sitio",
    confTabEndpointsConf: "Configuración de los puntos finales",
    confTabEndpointsConfDesc: "Define una lista de puntos finales disponibles",
    confTabDevEnvironmentConf: "Configuración del Ambiente Dev",
    confTabDevEnvironmentConfDesc: "Define una configuración de entorno de desarrollo",
    confTabTargetsConf: "Configuración de objetivos",
    confTabTargetsConfDesc: "Define una lista de objetivos para la forma de fuente de datos utilizada",
    confTabRTEConf: "Configuración RTE",
    confTabRTEConfDesc: "Define la configuraciones de editores de texto enriquecido en formularios",
    confTabPreviewAssetConf: "Configuración de Vista Previa de Activos",
    confTabPreviewAssetConfDesc: "Define una lista de activos editables asociados con contenido XML",
    confTabPreviewComponentsConf: "Configuración de los Componentes de Vista Previa",
    confTabPreviewComponentsConfDesc: "Define una lista de componentes que se pueden crear de forma dinámica en la vista previa",
    confTabPreviewPanelConf: "Configuración del Panel de Vista Previa",
    confTabconfTabPreviewPanelConfDesc: "Define una lista de herramientas disponibles en la vista previa",
    confTabPersonasConf: "Configuración de las Personas",
    confTabPersonasConfDesc: "Personas define una lista de personajes disponibles para asumir en la vista previa",
    confTabNotificationConf: "Notification Configuration",
    confTabNotificationConfDesc: "Define una lista de mensajes de interfaz de usuario",
    confTabPermissionsMappings: "Asignación de Permisos",
    confTabPermissionsMappingsDesc: "Define un mapa de permisos y caminos",
    confTabRoleMappings: "Asignaciones de Roles",
    confTabRoleMappingsDesc: "Define una lista de funciones disponibles en el sitio",
    confTabSiteConf: "Configuración del Sitio",
    confTabSiteConfDesc: "Define la configuración general del sitio",
    confTabWorkflowConf: "Configuración del Flujo de Trabajo",
    confTabWorkflowConfDesc: "Define los flujos de trabajo disponibles en el sistema",

    /* Errors */
    errorTitle: ". Rellene todos los títulos de los campos y fuentes de datos.",
    errorName: ". Por favor, rellene el nombre de variable para: "
});
