CStudioAuthoring.Messages.registerBundle("siteDashboard", "es", {
    dashboardTitle: "Panel de Control de {0}",

    dashboardCollapseAll: "Desplegar todo",
    dashboardExpandAll: "Expandir todo",
    dashboardEdit: "Editar",

    approvedScheduledCollapseAll: "Desplegar todo",

    dashletFilterPages: "Páginas",
    dashletFilterComponents: "Componentes",
    dashletFilterDocuments: "Documentos",
    dashletFilterAssets: "Recursos",
    dashletFilterAll: "Todo",

    dashletGoLiveQueueTitle: "Articulos Esperando por Aprobación",
    dashletGoLiveCollapseAll: "Desplegar todo",
    dashletGoLiveExpandAll: "Expandir todo",
    dashletGoLiveShowInProgress: "Mostrar Artículos \"En-Progreso\" ",
    dashletGoLiveHideInProgress: "Esconder Artículos \"En-Progreso \" ",
    dashletGoLiveColPageName: "Nombre del Artículo",
    dashletGoLiveColEdit: "Editar",
    dashletGoLiveColURL: "URL",
    dashletGoLiveColPublishDate: "Fecha y Hora de Publicación",
    dashletGoLiveColLastEditedBy: "Ultima Edición por",
    dashletGoLiveColLastEditedDate: "Última Edición",
    dashletGoLivePages: "Páginas ({0})",
    dashletGoLiveComponents: "Componentes ({0})",
    dashletGoLiveAssets: "Recursos ({0})",
    dashletGoLiveEdit: "Editar",

    dashletApprovedSchedTitle: "Artículos Publicados",
    dashletApprovedSchedCollapseAll: "Desplegar todo",
    dashletApprovedSchedExpandAll: "Expandir todo",
    dashletApprovedSchedShow: "Mostrar",
    dashletApprovedSchedColGoLiveDate: "Fecha para ir en Vivo",
    dashletApprovedSchedColEdit: "Editar",
    dashletApprovedSchedColURL: "URL",
    dashletApprovedSchedColLastEdited: "Última Edición",
    dashletApprovedSchedFilterPages: "Páginas",
    dashletApprovedSchedFilterComponents: "Componentes",
    dashletApprovedSchedFilterDocuments: "Documentos",
    dashletApprovedSchedFilterAll: "Todo",

    showNumItems: "Mostrar",

    dashletRecentDeployTitle: "Recientemente Publicados",
    dashletRecentDeployCollapseAll: "Desplegar todo",
    dashletRecentDeployExpandAll: "Expandir todo",
    dashletRecentDeployShow: "Mostrar",
    dashletRecentDeployColMadeLiveDateDate: "Fecha de Publicación",
    dashletRecentDeployColEdit: "Editar",
    dashletRecentDeployColURL: "URL",
    dashletRecentDeployColEndpoint: "Servidor",
    dashletRecentDeployColDeployBy: "Publicado por",

    dashletMyRecentActivityTitle: "Mi actividad reciente",
    dashletMyRecentActivityHideLiveItems: "Enconder Artículos en Vivo",
    dashletMyRecentActivityShowLiveItems: "Mostrar Artículos en Vivo",
    ddashletMyRecentActivityShow: "Mostrar",
    dashletMyRecentActivityColPageName: "Nombre del Artículo",
    dashletMyRecentActivityColEdit: "Editar",
    dashletMyRecentActivityColURL: "URL",
    dashletMyRecentActivityColPublishDate: "Fecha de Publicación",
    dashletMyRecentActivityColLastEditedBy: "Ultima Edición por",
    dashletMyRecentActivityColMyLastEdit: "Mi Ultima Edición",

    dashletIconGuideTitle: "Icono de guía de flujo de trabajo ",
    dashletIconGuideNavigationPage: "Pagina de Navegación",
    dashletIconGuideFloatingPage: "Página flotante",
    dashletIconGuideComponent: "Componente",
    dashletIconGuideDocument: "Documento",
    dashletIconGuideStateNew: "Nunca Piblicado",
    dashletIconGuideStateDisabled: "Disabled",
    dashletIconGuideStateDeleted: "Eliminado",
    dashletIconGuideStateInProgress: "Editado",
    dashletIconGuideStateInWorkflow: "En Flujo de Trabajo",
    dashletIconGuideStateScheduled: "Programado",
    dashletIconGuideStateSystemProcessing: "Procesando",
    dashletIconGuideStateLocked: "Bloqueado para editar"

});

CStudioAuthoring.Messages.registerBundle("contextnav", "es", {
    siteContent: "Contenido del Sitio",

    wcmContentEdit: "Editar",
    wcmContentView: "Ver",
    wcmContentSubmit: "Solicitud de Publicación",
    wcmContentDelete: "Eliminar",
    wcmContentSubmitDelete: "Solicitud de Eliminación",
    wcmContentReject: "Rechazar",
    wcmContentSchedule: "Programar",
    wcmContentApprove: "Aprobar y Publicar",
    wcmContentDuplicate: "Duplicar",
    wcmContentHistory: "Hiltorial",
    wcmContentPageDisabled: "Page is disabled: When deployed, a live visitor will see page not found (404) error.",

    InProgress: "Editado",
    Deleted: "Eliminado",
    SubmittedforDelete: "Presentado para Eliminar",
    mixedStates: "Artículos (Estados Mixtos)",
    Submitted: "Presentado para Aprobar",
    Live: "En Vivo",
    Scheduled: "Programado",

    search: "Busqueda",

    logout: "Cerrar Sesión",

    variableLabel: "Ejemplos de Código de Plantilla"

});

CStudioAuthoring.Messages.registerBundle("forms", "es", {
    expandAll: "Expandir Todo",
    collapseAll: "Collapsar Todo",
    pageName: "Item Name",
    location: "Ubicación",
    sectionValidation: "{0} de {1} campos requeridos son invalidos",
    saveAndClose: "Guardar y Cerrar",
    saveAndPreview: "Salvar y Mostrar",
    cancel: "Cancelar",
    close: "Cerrar",
    repeatAddAnother: "Agregar Otro",
    repeatMoveUp: "Mover Arriba",
    repeatMoveDown: "Mover Abajo",
    repeatDelete: "Eliminar",
    errMissingRequirements: "You cannot save until all form requirements are satisfied",
    errSaveFailed: "Unable to save form content. Please try again or contact or your system administrator.",
    errOnRepeat: "Error on repeater operation: {0}",
    errFailedToLoadContent: "Error loading content: {0}",
    errExpectedIndexXml: "Not expecting file-name other than index.xml",
    ok: "Aceptar",
    yes: "Si",
    no: "No",
    submit:"Enviar",
    loading:"Cargando&hellip;",

    copy: "Copiar",
    copyDescription: "Por favor seleccione las subpaginas que le gustaria copar.<br/> Al pegar, se conservarán las sub-páginas seleccionadas y su jerarquía posicional.",
    page: "Página",
    loadingContents: "Loading contents ...",
    cut: "Cut",
    cutDescription: "Por favor seleccione las subpaginas que le gustaria cortar.<br/> Al pegar, se conservarán las sub-páginas seleccionadas y su jerarquía posicional.",

    create: "Crear",
    newFolderTitle: "Crear una carpeta nueva",
    newFolderBody: "Porfavor ingrese el nombre de la carpeta",
    newFolderLabel: "Nombre de la carpeta:",
    newFolderUpdating: "Creando la carpeta...",

    chooseContentType: "Elige un tipo de contenido",
    chooseContentTypeBody: "Las siguientes plantillas de inicio están disponibles para su uso dentro de esta sección.",
    chooseContentTypeLabel: "Nombre de la Plantilla:",
    chooseContentTypePreview: "Vista Previa:",

    cancelDialogHeader:"Crafter Studio",
    cancelDialogBody:"Desea cerrar este formulario sin guardar los cambios?",

    changeTemplateDialogTitle:"Advertencia: Cambiando el Tipo de Contenido",
    changeTemplateDialogSubTitle:"Crafter Studio",
    changeTemplateDialogBody:"La siguiente operación puede provocar la pérdida de datos. ¿Quieres continuar?",

    historyDialogTitle: "Historial de las Versiones",
    historyDialogSubTitle: "Historial mostrado para:",
    historyDialogTableRowVersion: "Versión",
    historyDialogTableRowTime: "Tiempo de Edición",
    historyDialogTableRowEditBy: "Editado por",
    historyDialogTableRowComment: "Comentario",
    historyDialogRevert: "Revertir",
    historyDialogLoadingWait: "Cargando, por favor esperar&hellip;",
    historyDialogNoVersionsFound: "No hay versiones encontradas.",
    historyDialogUnable:"No se puede cargar el historial de versiones.",
    historyDialogTryAgain:"Inténtalo de nuevo",

    deleteDialogTitle:"Eliminar",
    deleteDialogSubTitle:"Los siguientes elementos seleccionados serán eliminados:",
    deleteDialogSetLink:'Establecer todo para "Ahora"',
    deleteDialogPage:"Página",
    deleteDialogDelete:"Eliminar",
    deleteDialogNow:"Ahora",
    deleteDialogFeedBack:"Las dependencias deben comprobarse antes de enviarlas",
    deleteDialogNoItemsSelected:"No hay artículos seleccionados",

    deleteSubmitDialogTitle:"Enviar para su eliminación",
    deleteSubmitDialogTime:"¿Cuándo desea eliminar los artículos marcados?",
    deleteSubmitEmailMe:"Enviarme un correo cuando los artículos son eliminados.",
    deleteSubmitDialogAsSoon:"Lo antes posible."


});

CStudioAuthoring.Messages.registerBundle("search", "es", {
    defaultTitle: "WCM Search",
    searchButtonLabel: "Search",
    keywordsLabel: "Keywords (optional)",
    searchResults: "Search Results",
    showing: "(Showing {0}-{1} of {2})",
    hideDescriptions: "Hide Descriptions",
    showDescriptions: "Show Descriptions",
    show: "Show",
    sort: "Sort",
    sortRelevance: "Relevance",
    sortAlphabetical: "Alphabetical",
    sortCreateDate: "Create Date",
    pagePrevious: "Previous",
    pageNext: "Next",
    errSearchFailed: "Search Failed. Try adjusting your filters. Cause: If issue persists contact administrator with error: {0}",
    errNoResults: "Your search returned no results."
});

CStudioAuthoring.Messages.registerBundle("contentTypes", "es", {
    label: "Content Types",
    openExistingType: "Open Existing Type",
    createNewType: "Create New Type",
    save: "Save",
    saved: "Saved",
    saveFailed: "Save Failed",
    formSection: "Form Section",
    repeatingGroup: "Repeating Group",
    minOccurs: "Minimum Occurances",
    maxOccurs: "Maximum Occurances",
    formBasics: "Form Basics",
    formTitle: "title",
    description: "Description",
    objectType: "Object Type",
    contentType: "Content Type",
    datasourceBasics: "Data Source Basics",
    title: "Title",
    name: "Name",
    properties: "Properties",
    sectionBasics: "Section Basics",
    variableName: "Name / Variable Name",
    iceGroup: "ICE Group",
    fieldBasics: "Field Basics",
    defaultValue: "Default Value",
    help: "Help",
    properties: "Properties",
    constraints: "Constraints",
    propertiesExplorer: "Properties Explorer",
    controls: "Controls",
    datasources: "Data Sources"
});
