CREATE TABLE [dbo].[cstudio_DEPENDENCY](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[site] [nvarchar](35) NOT NULL,
	[source_path] [nvarchar](4000) NOT NULL,
	[target_path] [nvarchar](4000) NOT NULL,
	[type] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_cstudio_DEPENDENCY] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [cstudio_dependency_site_idx] ON [dbo].[cstudio_DEPENDENCY] ( [site] ASC )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY];

CREATE NONCLUSTERED INDEX [cstudio_dependency_sourcepath_idx] ON [dbo].[cstudio_DEPENDENCY] ( [site] ASC )WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY];