CStudioAuthoring.Messages.registerBundle("siteDashboard", "en", {
    dashboardTitle: "{0} Dashboard",

    dashboardCollapseAll: "Collapse All",
    dashboardExpandAll: "Expand All",
    dashboardEdit: "Edit",

    approvedScheduledCollapseAll: "Collapse All",

    dashletFilterPages: "Pages",
    dashletFilterComponents: "Components",
    dashletFilterDocuments: "Documents",
    dashletFilterAssets: "Assets",
    dashletFilterAll: "All",

    dashletGoLiveQueueTitle: "Items Waiting For Approval",
    dashletGoLiveCollapseAll: "Collapse All",
    dashletGoLiveExpandAll: "Expand All",
    dashletGoLiveShowInProgress: "Show \"In-Progress\" Items",
    dashletGoLiveHideInProgress: "Hide \"In-Progress\" Items",
    dashletGoLiveColPageName: "Item Name",
    dashletGoLiveColEdit: "Edit",
    dashletGoLiveColURL: "URL",
    dashletGoLiveColPublishDate: "Publish Date & Time",
    dashletGoLiveColLastEditedBy: "Last Edited By",
    dashletGoLiveColLastEditedDate: "Last Edited",
    dashletGoLivePages: "Pages ({0})",
    dashletGoLiveComponents: "Components ({0})",
    dashletGoLiveAssets: "Assets ({0})",
    dashletGoLiveEdit: "Edit",

    dashletApprovedSchedTitle: "Approved Scheduled Items",
    dashletApprovedSchedCollapseAll: "Collapse All",
    dashletApprovedSchedExpandAll: "Expand All",
    dashletApprovedSchedShow: "Show",
    dashletApprovedSchedColGoLiveDate: "Go Live Date",
    dashletApprovedSchedColEdit: "Edit",
    dashletApprovedSchedColURL: "URL",
    dashletApprovedSchedColLastEdited: "Last Edited",
    dashletApprovedSchedFilterPages: "Pages",
    dashletApprovedSchedFilterComponents: "Components",
    dashletApprovedSchedFilterDocuments: "Documents",
    dashletApprovedSchedFilterAll: "All",

    showNumItems: "Show",

    dashletRecentDeployTitle: "Recently Published",
    dashletRecentDeployCollapseAll: "Collapse All",
    dashletRecentDeployExpandAll: "Expand All",
    dashletRecentDeployShow: "Show",
    dashletRecentDeployColMadeLiveDateDate: "Publish Date",
    dashletRecentDeployColEdit: "Edit",
    dashletRecentDeployColURL: "URL",
    dashletRecentDeployColEndpoint: "Server",
    dashletRecentDeployColDeployBy: "Published By",
    dashletRecentDeployColLastEdited: "Last Edited",

    dashletMyRecentActivityTitle: "My Recent Activity",
    dashletMyRecentActivityHideLiveItems: "Hide Live Items",
    dashletMyRecentActivityShowLiveItems: "Show Live Items",
    ddashletMyRecentActivityShow: "Show",
    dashletMyRecentActivityColPageName: "Item Name",
    dashletMyRecentActivityColEdit: "Edit",
    dashletMyRecentActivityColURL: "URL",
    dashletMyRecentActivityColPublishDate: "Publish Date",
    dashletMyRecentActivityColLastEditedBy: "Last Edited By",
    dashletMyRecentActivityColMyLastEdit: "My Last Edit",

    dashletIconGuideTitle: "Workflow Icon Guide",
    dashletIconGuideNavigationPage: "Navigation Page",
    dashletIconGuideFloatingPage: "Floating Page",
    dashletIconGuideComponent: "Component",
    dashletIconGuideDocument: "Document",
    dashletIconGuideStateNew: "Never published",
    dashletIconGuideStateDisabled: "Disabled",
    dashletIconGuideStateDeleted: "Deleted",
    dashletIconGuideStateInProgress: "Edited",
    dashletIconGuideStateInWorkflow: "In Workflow",
    dashletIconGuideStateScheduled: "Scheduled",
    dashletIconGuideStateSystemProcessing: "Processing",
    dashletIconGuideStateLocked: "Locked for edit"

});

CStudioAuthoring.Messages.registerBundle("contextnav", "en", {
    siteContent: "Site Content",

    wcmContentEdit: "Edit",
    wcmContentView: "View",
    wcmContentSubmit: "Request Publish",
    wcmContentDelete: "Delete",
    wcmContentSubmitDelete: "Request Delete",
    wcmContentReject: "Reject",
    wcmContentSchedule: "Schedule",
    wcmContentApprove: "Approve & Publish",
    wcmContentDuplicate: "Duplicate",
    wcmContentHistory: "History",
    wcmContentPageDisabled: "Page is disabled: When deployed, a live visitor will see page not found (404) error.",

    InProgress: "Edited",
    Deleted: "Deleted",
    SubmittedforDelete: "Submitted for Delete",
    mixedStates: "Items (Mixed States)",
    Submitted: "Submitted for Publish",
    Live: "Live",
    Scheduled: "Scheduled",

    search: "Search",

    logout: "Log Out",

    variableLabel: "Template code examples"

});

CStudioAuthoring.Messages.registerBundle("previewTools", "en", {
    previewToolsTitle: "Preview Tools",
    inContextEditing: "In-Context Editing",
    pageComponents: "Page Components",
    responsivePreview: "Responsive Preview",
    desktop: "Desktop",
    browser: "Browser",
    iphone: "iPhone5iPhone5S",
    iPad: "iPad",
    targeting: "Targeting",
    analytics: "Analytics",
    translation: "Translation",
    inContextEditOn: "In-Context Edit On",
    inContextEditOff: "In-Context Edit Off",
    publishingChannel: "Publishing Channel",
    web: "Web",
    smartPhone: "Smart Phone",
    tablet: "Tablet",
    multiVariantTesting: "Multi-Variant Testing",
    YellowVsBlue: "Yellow vs Blue Mask on Home",
    yellow: "Yellow",
    blue: "Blue",
    FacetedVsKeyword: "Faceted Search vs Keyword",
    faceted: "Faceted",
    facetedKeyword: "Faceted + Keyword",
    keywordOnly: "Keyword Only",
    HomeRedVsBlue: "Home Red vs Blue CTA Buttons",
    red: "Red",
    catalogPageSorting: "Catalog Page Sorting",
    arrivalDate: "Arrival Date",
    priceHightoLow: "Price High to Low",
    priceLowtoHigh: "Price Low to High",
    editTemplate: "Edit Template",
    jumpToRegion: "Jump to Region",
    dimensionsPx: "Dimensions (px)",
    presets: "Presets",
    custom: "Custom",
    addComponent: "Add Component",
    done: "Done",
    general: "General",
    components: "Components",
    persona: "Persona",
    properties: "Properties",
    assume: "Assume",
    update: "Update",
    active: "Active",
    reportsOff: "Reports Off",
    reportsError: "Unable to render report due to error",
    addComponent :"Add Component",
    done: "done",
    components: "Components",
    general: "General",
    text: "text"

});

CStudioAuthoring.Messages.registerBundle("siteDropdown", "en", {
    pages: "Pages",
    Pages: "Pages",
    page: "Page",
    components: "Components",
    Components: "Components",
    component: "Component",
    staticassets: "Static Assets",
    templates: "Templates",
    scripts: "Scripts",
    analyticsDashboard: "Analytics Dashboard",
    adminConsole: "Admin Console",
    previewSync: "Preview Sync",
    allSites: "All Sites",
    newContent: "New Content",
    newFolder: "New Folder",
    upload: "Upload",
    edit: "Edit",
    view: "View",
    changeTemplate: "Change Template",
    delete: "Delete",
    cut: "Cut",
    copy: "Copy",
    paste: "Paste",
    history: "History",
    unlock: "Unlock",
    noActionsAvailable: "No Actions Available",
    createFolder: "Create Folder",
    createTemplate: "Create Template",
    createController: "Create Controller",
    bulkUploadAssets: "Bulk Upload Assets",
    lastEdited: "Last Edited",
    editedBy: "Edited by",
    lockedBy: "Locked by",
    status: "Status",
    scheduled: "Scheduled",
    loading: "Loading...",

    /*tooltip-Status*/
    statusDeleted: "Deleted",
    statusScheduledForDelete: "Scheduled for Delete",
    statusSubmittedForDelete: "Submitted for Delete",
    statusAndDisabled: "and Disabled",
    statusProcessing: "Processing",
    statusInProgress: "In Progress",
    statusLive: "Live",
    statusAnd: "and",
    statusSubmitted: "Submitted",
    statusScheduled: "Scheduled",
    statusDisabled: "Disabled"

});

CStudioAuthoring.Messages.registerBundle("forms", "en", {
    expandAll: "Expand All",
    collapseAll: "Collapse All",
    pageName: "Item Name",
    location: "Location",
    sectionValidation: "{0} of {1} field requirements are invalid",
    saveAndClose: "Save and Close",
    saveAndPreview: "Save and Preview",
    save: "Save",
    cancel: "Cancel",
    close: "Close",
    repeatAddAnother: "Add Another",
    repeatMoveUp: "Move Up",
    repeatMoveDown: "Move Down",
    repeatDelete: "Delete",
    errMissingRequirements: "You cannot save until all form requirements are satisfied",
    errSaveFailed: "Unable to save form content. Please try again or contact or your system administrator.",
    errOnRepeat: "Error on repeater operation: {0}",
    errFailedToLoadContent: "Error loading content: {0}",
    errExpectedIndexXml: "Not expecting file-name other than index.xml",
    ok: "Ok",
    yes: "Yes",
    no: "No",
    submit:"Submit",
    loading:"Loading&hellip;",
    viewSample: "View Sample",
    hideSample: "Hide Sample",
    clearCache: "Clear Cache",

    copy: "Copy",
    copyDescription: "Please select any of the sub-pages you would like to batch copy.<br/> When pasting, any selected sub-pages and their positional heirarchy will be retained.",
    page: "Page",
    loadingContents: "Cargando Contenidos ...",
    cut: "Cut",
    cutDescription: "Please select any of the sub-pages you would like to batch cut.<br/> When pasting, any selected sub-pages and their positional heirarchy will be retained.",

    create: "Create",
    newFolderTitle: "Create a New Folder",
    newFolderBody: "Please enter a folder name",
    newFolderLabel: "Folder Name:",
    newFolderUpdating: "Creating a folder...",

    chooseContentType: "Choose Content Type",
    chooseContentTypeBody: "The following starter templates are available for use within this section.",
    chooseContentTypeLabel: "Template Name:",
    chooseContentTypePreview: "Preview:",

    cancelDialogHeader:"Crafter Studio",
    cancelDialogBody:"Close this form without saving changes?",

    changeTemplateDialogTitle:"Warning: Change Content Type",
    changeTemplateDialogSubTitle:"Crafter Studio",
    changeTemplateDialogBody:"The following operation may result in data loss. Would you like to proceed?",

    historyDialogTitle: "Version History",
    historyDialogSubTitle: "History shown for:",
    historyDialogTableRowVersion: "Version",
    historyDialogTableRowTime: "Edit Time",
    historyDialogTableRowEditBy: "Edited By",
    historyDialogTableRowComment: "Comment",
    historyDialogRevert: "Revert",
    historyDialogLoadingWait: "Loading, please wait&hellip;",
    historyDialogNoVersionsFound: "No versions found.",
    historyDialogUnable:"Unable to load version history.",
    historyDialogTryAgain:"Try again",

    deleteDialogTitle: "Delete",
    deleteDialogSubTitle: "The following checked items will be deleted:",
    deleteDialogSetLink: 'Set everything to "Now"',
    deleteDialogPage: "Page",
    deleteDialogDelete: "Delete",
    deleteDialogNow: "Now",
    deleteDialogFeedBack: "Dependencies must be checked before you can submit",
    deleteDialogNoItemsSelected: "No items selected",

    deleteSubmitDialogTitle: "Submit for deletion",
    deleteSubmitDialogTime: "When would you like the checked item(s) to be deleted?",
    deleteSubmitEmailMe: "Email me when my items are deleted",
    deleteSubmitDialogAsSoon: "As soon as possible.",

    approveDialogTitle: "Approve for Publish",
    approveDialogSubTitle: "The following checked items will go live.",
    approveDialogPage: "Page",
    approveDialogOriginalSchedule: "Original Schedule",
    approveDialogSubmissionComment: "Submission Comment",
    approveDialogSelectedScheduling: "Selected Item Scheduling",
    approveDialogItemsLiveNow: "Items should go live now.",
    approveDialogItemsLiveDate: "Items go live on a specific date &amp; time",
    approveDialogPublishContent: "Publish Content",
    approveDialogPublishingOptions: "Publishing Options",
    approveDialogBroadcastUpdate: "Broadcast content update",

    requestApproveDialogTitle: "Request Publish",
    requestApproveDialogSubTitle: "When would you like the checked item(s) to go live?",
    requestApproveDialogEmailMe: "Email me when items go live.",

    newContTypeDialogTitle: "Create Content Type",
    newContTypeDialogDisplayLabel: "Display Label",
    newContTypeDialogContentTypeName: "Content Type Name",
    newContTypeDialogType: "Type",
    component: "Component",
    newContTypeDialogLabelMsg: "Provide a display label for this content type",
    newContTypeDialogContentTypeNamelMsg: "Provide a system name for this content type",
    newContTypeDialogTypeMsg: "Select the type for this content type",

    adminHelpDialogTitle: "Field Content",

    adminKeyValDialogTitle: "Values",
    adminKeyValDialogKey: "Key",
    adminKeyValDialogValue: "Value",
    addAnother: "Add Another",

    supportedChannelsDialogLabel: "Label",
    supportedChannelsDialogName: "Name",
    supportedChannelsDialogSize :"Size",

    setStatedDialogTitle: "Select States",
    setStatedDialogSetStates: "Set States",
    setStatedDialogSystemProcessing: "System Processing",

    setQueueDialogTitle: "Select States",
    setQueueDialogCancelDeployment: "Cancel Deployment",
    setQueueDialogSystemProcessing: "System Processing",

    currentPage: "Current Page"

});

CStudioAuthoring.Messages.registerBundle("search", "en", {
    defaultTitle: "WCM Search",
    searchButtonLabel: "Search",
    keywordsLabel: "Keywords (optional)",
    searchResults: "Search Results",
    showing: "(Showing {0}-{1} of {2})",
    hideDescriptions: "Hide Descriptions",
    showDescriptions: "Show Descriptions",
    show: "Show",
    sort: "Sort",
    sortRelevance: "Relevance",
    sortAlphabetical: "Alphabetical",
    sortCreateDate: "Create Date",
    pagePrevious: "Previous",
    pageNext: "Next",
    resultsEdited: "Edited",
    resultsBy: "By",
    resultsUnknownType: "Unknown Type",
    resultsTemplate: "Template",
    errSearchFailed: "Search Failed. Try adjusting your filters. Cause: If issue persists contact administrator with error: {0}",
    errNoResults: "Your search returned no results."
});

CStudioAuthoring.Messages.registerBundle("contentTypes", "en", {
    contentTypes: "Content Types",
    configuration: "Configuration",
    workflowJobs: "Workflow Jobs",
    workflowStates: "Workflow States",
    loggingLevels: "Logging Levels",
    logConsole: "Log Console",
    deploymentQueues: "Deployment Queues",
    label: "Content Types",
    openExistingType: "Open Existing Type",
    createNewType: "Create New Type",
    save: "Save",
    saved: "Saved",
    saveFailed: "Save Failed",
    formSection: "Form Section",
    repeatingGroup: "Repeating Group",
    minOccurs: "Minimum Occurances",
    maxOccurs: "Maximum Occurances",
    formBasics: "Form Basics",
    formTitle: "title",
    description: "Description",
    objectType: "Object Type",
    contentType: "Content Type",
    datasourceBasics: "Data Source Basics",
    title: "Title",
    name: "Name",
    properties: "Properties",
    sectionBasics: "Section Basics",
    variableName: "Name / Variable Name",
    iceGroup: "ICE Group",
    fieldBasics: "Field Basics",
    defaultValue: "Default Value",
    help: "Help",
    constraints: "Constraints",
    propertiesExplorer: "Properties Explorer",
    controls: "Controls",
    datasources: "Data Sources",
    defaultOpen: "Default Open",
    showInNav: "Show In Nav",
    descriptorMapper: "Descriptor Mapper",

    /*Controls*/
    textArea: "Text Area",
    richTextEditor: "Rich Text Editor",
    input: "Input",
    dropdown: "Dropdown",
    dateTime: "Date / Time",
    checkBox: "Check Box",
    groupedCheckboxes: "Grouped Checkboxes",
    itemSelector: "Item Selector",
    image: "Image",
    video: "Video",
    label: "Label",
    pageOrder: "Page Order",
    fileName: "File Name",
    autoFilename: "Auto Filename",
    forceHTTPS: "Force HTTPS",
    disabled: "Disabled",
    flash: "Flash",
    internalName: "Internal Name",

    /*Datasources */
    childContent: "Child Content",
    imageUploadedDesktop: "Image Uploaded from Desktop",
    DAMImage: "DAM Image Flickr",
    fileUploadedDesktop: "File Uploaded from Desktop",
    flashUploadedDesktop: "Flash Uploaded from Desktop",
    videoUploadedDesktop: "Video Uploaded from Desktop",
    staticKeyValuePairs: "Static Key Value Pairs",
    configuredListOfPairs: "Configured List of Pairs",
    fileBrowse: "File Browse",
    hubspotForms: "Hubspot Forms",
    imageFromRepository: "Image from repository",
    salesforceCampaigns: "Salesforce Campaigns",
    treeContent: "Tree content",

    /*Properties*/
    size: "Size",
    maxLength: "Max Length",
    width: "Width",
    height: "Height",
    allowResize: "Allow Resize",
    forceRootBlockP: "Force Root Block p Tag",
    forcePNewLines: "Force p tags New Lines",
    forceBRNewLines: "Force br New Lines",
    requireImageAlt: "Require Image Alt Tag",
    supportedChannels: "Supported Channels",
    RTEConfiguration: "RTE Configuration",
    imageManager: "Image Manager",
    showDate: "Show Date",
    showTime: "Show Time",
    setNowLink: "Set Now Link",
    populated: "Populated",
    allowPastDate: "Allow Past Date",
    readonly: "Readonly",
    readonlyOnEdit: "Readonly on Edit",
    datasource: "Data Source",
    showSelectAll: 'Show "Select All"',
    allowEmptyValue: "Allow Empty Value",
    thumbnailWidth: "Thumbnail Width",
    displaySize: "Display Size",
    text: "Text",
    minSize: "Min Size",
    maxSize: "Max Size",
    itemManager: "Item Manager",
    disableFlatteningSearch: "Disable Flattening for Search",
    singleValueFilename: "Use single value filename (backward compat)",
    columns: "Columns",
    rows: "Rows",
    dataType: "Data Type",
    listName: "List Name",
    repositoryPath: "Repository Path",
    string: "String",
    integer: "Integer",
    float: "Float",
    date: "Date",
    HTML: "HTML",
    options: "Options",
    showKeys: "Show keys (item sel. only)",
    taxonomyName: "Taxonomy Name",
    defaultType: "Default Type",
    displayTemplate: "Display Template",
    mergeStrategy: "Merge Strategy",

    /*Restrictions*/
    required: "Required",
    minimumSelection: "Minimum Selection",
    matchPattern: "Match Pattern",
    allowDuplicate: "Allow Duplicates",

    /*Values*/
    noDatasources: "No datasources available for this control",
    editMessage: "Edit message",
    setMessage: "Set message",

    /*States Workflow*/
    setStatedTabID: "ID",
    setStatedTabState: "State",
    setStatedTabSystemProcessing: "System Processing",
    setStatedTabSelectAll: "Select All",
    false: "False",
    true: "True",

    /*Deployment Queues*/
    setQueueTabSelectAll: "Select All",
    setQueueTabID: "ID",
    setQueueTabPath: "Path",
    setQueueTabEnvironment: "Environment",
    setQueueTabUser: "User",
    setQueueTabState: "State",
    setQueueTabAction: "Action",
    setQueueTabScheduledDate: "Scheduled Date",

    /*Jobs Workflow*/
    jobWorkflowTabAct: "Act",
    jobWorkflowTabJobID: "Job ID",
    jobWorkflowTabProcessName: "Process Name",
    jobWorkflowTabCreatedDate: "Fecha de <br/> Creación",
    jobWorkflowTabModifiedDate: "Fecha de <br/> Modificación",
    jobWorkflowTabSiteId: "Site Id",
    jobWorkflowTabItemsInJob: "Items<br/>in Job",
    jobWorkflowTabProperties: "Properties",
    jobWorkflowTabStatus: "Status",

    /*Loggin Levels*/
    logginLevelsTabLogger: "Logger",
    logginLevelsTabCurrentLevel: "Current Level",
    logginLevelsTabChangeLevel: "Change Level To",
    debug: "debug",
    warn: "warn",
    info: "info",
    error: "error",

    /*Configuration*/
    confTabSelectConf: "Select Configuration",
    confTabConfigurations: "Configurations",
    confTabConfDesc: "Defines this list of configurations",
    confTabAdminTools: "Admin Tools",
    confTabAdminToolsDesc: "Defines the list of admin tools available",
    confTabAnalyticsDashboardConf: "Analytics Dashboard Configuration",
    confTabAnalyticsDashboardConfDesc: "Defines types of reports shown on Analytics Dashboard",
    confTabAnalyticsPreviewConf: "Analytics Preview Configuration",
    confTabAnalyticsReportConf: "Analytics Report Configuration",
    confTabContextualNavigationConf: "Contextual Navigation Configuration",
    confTabContextualNavigationConfDesc: "Defines modules on the site contextual navigation bar",
    confTabSiteDropdownConf: "Site Dropdown Configuration",
    confTabSiteDropdownConfDesc: "Defines modules on the site dropdown bar",
    confTabEndpointsConf: "Endpoints Configuration",
    confTabEndpointsConfDesc: "Defines a list of end points available",
    confTabDevEnvironmentConf: "Dev Environment Configuration",
    confTabDevEnvironmentConfDesc: "Defines a dev environment configuration",
    confTabTargetsConf: "Targets Configuration",
    confTabTargetsConfDesc: "Defines a list of targets used for form datasource",
    confTabRTEConf: "RTE Configuration",
    confTabRTEConfDesc: "Defines Rich Text Editors configurations in form",
    confTabPreviewAssetConf: "Preview Asset Configuration",
    confTabPreviewAssetConfDesc: "Defines a list of editable assets associated with XML contents",
    confTabPreviewComponentsConf: "Preview Components Configuration",
    confTabPreviewComponentsConfDesc: "Defines a list of components that can be created dynamically in preview",
    confTabPreviewPanelConf: "Preview Panel Configuration",
    confTabconfTabPreviewPanelConfDesc: "Defines a list of tools available in preview",
    confTabPersonasConf: "Personas Configuration",
    confTabPersonasConfDesc: "Defines a list of personas available to assume in preview",
    confTabNotificationConf: "Notification Configuration",
    confTabNotificationConfDesc: "Defines a list of UI messages",
    confTabPermissionsMappings: "Permissions Mapping",
    confTabPermissionsMappingsDesc: "Defines a map of permissions and paths",
    confTabRoleMappings: "Role Mappings",
    confTabRoleMappingsDesc: "Defines a list of roles available in site",
    confTabSiteConf: "Site Configuration",
    confTabSiteConfDesc: "Defines the general site configuration",
    confTabWorkflowConf: "Workflow Configuration",
    confTabWorkflowConfDesc: "Defines workflows available in the system",

    /* Errors */
    errorTitle: ". Please fill every title for fields and datasources.",
    errorName: ". Please fill variable name for: "

});
