
CStudioAuthoring.Messages.registerBundle("siteDashboard", "en",
    { dashboardTitle: "{0} Dashboard",
  
      dashletFilterPages: "Pages",
      dashletFilterComponents: "Components",
      dashletFilterDocuments: "Documents",
      dashletFilterAssets: "Assets",
      dashletFilterAll: "All",

      dashletGoLiveQueueTitle: "Items Waiting For Approval",
      dashletGoLiveCollapseAll: "Collapse All",
      dashletGoLiveExpandAll: "Expand All",
      dashletGoLiveShowInProgress: "Show \"In-Progress\" Items",
      dashletGoLiveHideInProgress: "Hide \"In-Progress\" Items",
      dashletGoLiveColPageName: "Item Name",
      dashletGoLiveColEdit: "Edit",
      dashletGoLiveColURL: "URL",
      dashletGoLiveColPublishDate: "Publish Date & Time",
      dashletGoLiveColLastEditedBy: "Last Edited By",
      dashletGoLiveColLastEditedDate: "Last Edited",
      dashletGoLivePages: "Pages ({0})",
      dashletGoLiveComponents: "Components ({0})",
      dashletGoLiveAssets: "Assets ({0})",
      dashletGoLiveEdit: "Edit",

      dashletApprovedSchedTitle: "Approved Scheduled Items",
      dashletApprovedSchedCollapseAll: "Collapse All",
      dashletApprovedSchedExpandAll: "Expand All",
      dashletApprovedSchedShow: "Show",
      dashletApprovedSchedColGoLiveDate: "Go Live Date",
      dashletApprovedSchedColEdit: "Edit",
      dashletApprovedSchedColURL: "URL",
      dashletApprovedSchedColLastEdited: "Last Edited",

      dashletRecentDeployTitle: "Recently Published",
      dashletRecentDeployCollapseAll: "Collapse All",
      dashletRecentDeployExpandAll: "Expand All",
      dashletRecentDeployShow: "Show",
      dashletRecentDeployColMadeLiveDateDate: "Publish Date",
      dashletRecentDeployColEdit: "Edit",
      dashletRecentDeployColURL: "URL",
      dashletRecentDeployColEndpoint: "Server",
      dashletRecentDeployColDeployBy: "Published By",

      dashletMyRecentActivityTitle: "My Recent Activity",
      dashletMyRecentActivityHideLiveItems: "Hide Live Items",
      dashletMyRecentActivityShowLiveItems: "Show Live Items", 
      ddashletMyRecentActivityShow: "Show",
      dashletMyRecentActivityColPageName: "Item Name",
      dashletMyRecentActivityColEdit: "Edit",
      dashletMyRecentActivityColURL: "URL",
      dashletMyRecentActivityColPublishDate: "Publish Date",
      dashletMyRecentActivityColLastEditedBy: "Last Edited By",
      dashletMyRecentActivityColMyLastEdit: "My Last Edit",

      dashletIconGuideTitle: "Workflow Icon Guide",
      dashletIconGuideNavigationPage: "Navigation Page",
      dashletIconGuideFloatingPage: "Floating Page",
      dashletIconGuideComponent: "Component",
      dashletIconGuideDocument: "Document",
      dashletIconGuideStateNew: "Never published",
      dashletIconGuideStateDisabled: "Disabled",
      dashletIconGuideStateDeleted: "Deleted",
      dashletIconGuideStateInProgress: "Edited",
      dashletIconGuideStateInWorkflow: "In Workflow",
      dashletIconGuideStateScheduled: "Scheduled",
      dashletIconGuideStateSystemProcessing: "Processing",
      dashletIconGuideStateLocked: "Locked for edit",
});

CStudioAuthoring.Messages.registerBundle("contextnav", "en",
    {  siteContent: "Site Content",
  
});
