
CStudioAuthoring.Messages.registerBundle("siteDashboard", "en",
    { dashboardTitle: "{0} Dashboard",
    approvedScheduledCollapseAll: "FOO!",
      dashletFilterPages: "Pages",
      dashletFilterComponents: "Components",
      dashletFilterDocuments: "Documents",
      dashletFilterAssets: "Assets",
      dashletFilterAll: "All",

      dashletGoLiveQueueTitle: "Items Waiting For Approval",
      dashletGoLiveCollapseAll: "Collapse All",
      dashletGoLiveExpandAll: "Expand All",
      dashletGoLiveShowInProgress: "Show \"In-Progress\" Items",
      dashletGoLiveHideInProgress: "Hide \"In-Progress\" Items",
      dashletGoLiveColPageName: "Item Name",
      dashletGoLiveColEdit: "Edit",
      dashletGoLiveColURL: "URL",
      dashletGoLiveColPublishDate: "Publish Date & Time",
      dashletGoLiveColLastEditedBy: "Last Edited By",
      dashletGoLiveColLastEditedDate: "Last Edited",
      dashletGoLivePages: "Pages ({0})",
      dashletGoLiveComponents: "Components ({0})",
      dashletGoLiveAssets: "Assets ({0})",
      dashletGoLiveEdit: "Edit",

      dashletApprovedSchedTitle: "Approved Scheduled Items",
      dashletApprovedSchedCollapseAll: "Collapse All",
      dashletApprovedSchedExpandAll: "Expand All",
      dashletApprovedSchedShow: "Show",
      dashletApprovedSchedColGoLiveDate: "Go Live Date",
      dashletApprovedSchedColEdit: "Edit",
      dashletApprovedSchedColURL: "URL",
      dashletApprovedSchedColLastEdited: "Last Edited",

      dashletRecentDeployTitle: "Recently Published",
      dashletRecentDeployCollapseAll: "Collapse All",
      dashletRecentDeployExpandAll: "Expand All",
      dashletRecentDeployShow: "Show",
      dashletRecentDeployColMadeLiveDateDate: "Publish Date",
      dashletRecentDeployColEdit: "Edit",
      dashletRecentDeployColURL: "URL",
      dashletRecentDeployColEndpoint: "Server",
      dashletRecentDeployColDeployBy: "Published By",

      dashletMyRecentActivityTitle: "My Recent Activity",
      dashletMyRecentActivityHideLiveItems: "Hide Live Items",
      dashletMyRecentActivityShowLiveItems: "Show Live Items", 
      ddashletMyRecentActivityShow: "Show",
      dashletMyRecentActivityColPageName: "Item Name",
      dashletMyRecentActivityColEdit: "Edit",
      dashletMyRecentActivityColURL: "URL",
      dashletMyRecentActivityColPublishDate: "Publish Date",
      dashletMyRecentActivityColLastEditedBy: "Last Edited By",
      dashletMyRecentActivityColMyLastEdit: "My Last Edit",

      dashletIconGuideTitle: "Workflow Icon Guide",
      dashletIconGuideNavigationPage: "Navigation Page",
      dashletIconGuideFloatingPage: "Floating Page",
      dashletIconGuideComponent: "Component",
      dashletIconGuideDocument: "Document",
      dashletIconGuideStateNew: "Never published",
      dashletIconGuideStateDisabled: "Disabled",
      dashletIconGuideStateDeleted: "Deleted",
      dashletIconGuideStateInProgress: "Edited",
      dashletIconGuideStateInWorkflow: "In Workflow",
      dashletIconGuideStateScheduled: "Scheduled",
      dashletIconGuideStateSystemProcessing: "Processing",
      dashletIconGuideStateLocked: "Locked for edit",

});

CStudioAuthoring.Messages.registerBundle("contextnav", "en", { 
      siteContent: "Site Content",

      wcmContentEdit: "Edit",
      wcmContentView: "View",
      wcmContentSubmit: "Request Publish",
      wcmContentDelete: "Delete",
      wcmContentSubmitDelete: "Request Delete",
      wcmContentReject: "Reject",
      wcmContentSchedule: "Schedule",
      wcmContentApprove: "Approve & Publish",
      wcmContentDuplicate: "Duplicate",
      wcmContentHistory: "History",
      wcmContentPageDisabled: "Page is disabled: When deployed, a live visitor will see page not found (404) error.",
      
      InProgress: "Edited",
      Deleted: "Deleted",
      SubmittedforDelete: "Submitted for Delete",
      mixedStates: "Items (Mixed States)",
      Submitted: "Submitted for Publish",
      Live: "Live",
      Scheduled: "Scheduled",

      search: "Search",

      logout: "Log Out",

});

CStudioAuthoring.Messages.registerBundle("forms", "en", { 
      expandAll: "Expand All",
      collapseAll: "Collapse All",
      pageName: "Item Name",
      location: "Location",
      sectionValidation: "{0} of {1} field requirements are invalid",
      saveAndClose: "Save and Close",
      saveAndPreview: "Save and Preview",
      cancel: "Cancel",
      close: "Close",
      repeatAddAnother: "Add Another",
      repeatMoveUp: "Move Up",
      repeatMoveDown: "Move Down",
      repeatDelete: "Delete",
      errMissingRequirements: "You cannot save until all form requirements are satisfied",
      errSaveFailed: "Unable to save form content. Please try again or contact or your system administrator.",
      errOnRepeat: "Error on repeater operation: {0}",
      errFailedToLoadContent: "Error loading content: {0}",
      errExpectedIndexXml: "Not expecting file-name other than index.xml",
      

});

CStudioAuthoring.Messages.registerBundle("search", "en", { 
      defaultTitle: "WCM Search",
      searchButtonLabel: "Search",
      keywordsLabel: "Keywords (optional)",
      searchResults: "Search Results", 
      showing: "(Showing {0}-{1} of {2})", 
      hideDescriptions: "Hide Descriptions",
      showDescriptions: "Show Descriptions",
      show: "Show",
      sort: "Sort",
      sortRelevance: "Relevance",
      sortAlphabetical: "Alphabetical",
      sortCreateDate: "Create Date",
      pagePrevious: "Previous",
      pageNext: "Next",
      errSearchFailed: "Search Failed. Try adjusting your filters. Cause: If issue persists contact administrator with error: {0}",
      errNoResults: "Your search returned no results.",
});

CStudioAuthoring.Messages.registerBundle("contentTypes", "en", { 
      label: "Content Types",
      openExistingType: "Open Existing Type",
      createNewType: "Create New Type",
      save:"Save",
      saved:"Saved",
      saveFailed:"Save Failed",
      formSection:"Form Section",
      repeatingGroup: "Repeating Group",
      minOccurs: "Minimum Occurances",
      maxOccurs: "Maximum Occurances",
      formBasics: "Form Basics",
      formTitle: "title",
      description: "Description",
      objectType: "Object Type",
      contentType: "Content Type",
      datasourceBasics: "Data Source Basics",
      title: "Title",
      name: "Name",
      properties: "Properties",
      sectionBasics: "Section Basics",
      variableName: "Name / Variable Name",
      iceGroup: "ICE Group",
      fieldBasics: "Field Basics",
      defaultValue: "Default Value",
      help: "Help",
      properties: "Properties",
      constraints: "Constraints",
      propertiesExplorer: "Properties Explorer",
      controls: "Controls",
      datasources: "Data Sources",
});
